### ISSUE TITLE
Remove pry-syntax-hacks gem from Gemfile

### ISSUE THREAD

**Issue by sebroeder** [SciRuby/iruby#10]
After I did a `bundle install` from the Gemfile I get the following error message every time I start Pry/Iruby console:

```ruby
require 'pry-syntax-hacks' # Failed, saying: undefined method `retrieve_line' for class `Pry'
```

```bash
$ pry --version
Pry version 0.10.1 on Ruby 2.2.0
```

Does it work for anybody else?

There is an 2 years old open issue for this at ConradIrwin/pry-syntax-hacks#2 but the gem is not maintained anymore for almost 3 years, falling behind the very active development of the main pry gem. Since it not working anymore, unmaintained and even has *hacks* in its name, I suggest we remove it from the Gemfile.

Does this have any negative effects on the pry backend for IRuby I overlooked?

**Comment by liudangyi** [comment]
Pry can be extended by [plugins](https://github.com/pry/pry/wiki/Plugins#Plugin_what_is).

So, just remove `gem 'pry-syntax-hacks'` from `Gemfile`.

**Comment by minad** [comment]
removed in master
