### ISSUE TITLE
iruby consumes 100% cpu

### ISSUE THREAD

**Issue by kylekyle** [SciRuby/iruby#101]
A colleague today observed that iruby kernels consume 100% of the cpu. I debugged the issue, which came down to this line in `lib/iruby/session/ffi_rzmq.rb`:

``` ruby
  rc = socket.recv_string(frame,1)                                                                                         
```

This checks ZMQ for a message without blocking. It is part of a while loop that is continuously polling, which is where the cpu consumption is coming from. I removed the `DONTWAIT` flag and cpu consumption dropped to zero and everything seemed to work fine. In fact, (but this could have been in my head) things seemed a lot snappier. 

I'm not a ZMQ expert, so does anyone know why we need the `DONTWAIT` flag? Is it safe to remove?

**Comment by matugm** [comment]
I just tested this. I disabled the `DONTWAIT` & my CPU usage drops to almost nothing, but normally it's 100% while IRuby is running.

I didn't notice any downsides from removing that flag, so I think it's probably safe to remove :)
