### ISSUE TITLE
Export as .rb doesn't work

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/iruby#104]
I tried exporting the notebook to Ruby file (.rb) by going to File -> Download As -> Ruby.

I got the following error:

```
Could not import nbconvert: No module named entrypoints
```

**Comment by matugm** [comment]
I can't seem to reproduce this.

I think it would be helpful if you could provide a copy of a notebook that you aren't able to export (or does this happen with all notebooks? Even a simple notebook with just one cell?).

**Comment by kojix2** [comment]
I can't seem to reproduce this too.

https://github.com/jupyter/nbconvert/issues/289

**Comment by kojix2** [comment]
Hello.
Looking at the error message, this problem seems to be a problem of building Python's environment rather than Ruby. Since there is no similar report for 2 years, I would close this issue.

Please feel free to reopen if there is a problem.
