### ISSUE TITLE
Support cztop

### ISSUE THREAD

**Issue by mrkn** [SciRuby/iruby#106]
[cztop](https://github.com/paddor/cztop) is a new czmq binding built with ffi.
It is actively maintained now while rbczmq and ffi-rzmq are not actively maintained.
[Kou tried to get admin-bit of rbczmq, but it was failed](https://github.com/methodmissing/rbczmq/issues/61).
I think it will be a new standard zeromq library because the author actively maintains it.
So we need to support cztop.

**Comment by kylekyle** [comment]
I'll look into adding support.
