### ISSUE TITLE
Replace ffi-rzmq with rbczmq

### ISSUE THREAD

**Issue by liudangyi** [SciRuby/iruby#11]
[They suggest](https://github.com/chuckremes/ffi-rzmq#future-support) using [methodmissing/rbczmq](https://github.com/methodmissing/rbczmq). But I don't see much difference between them.

**Comment by minad** [comment]
Thanks for looking into this. "permanent maintainance mode" doesn't sound good. We should definitely switch.

**Comment by mohawkjohn** [comment]
Permanent maintenance mode? WTH does that mean?

**Comment by minad** [comment]
@liudangyi Do you have time to work on this and #1 (protocol update) in the next days? It would improve your chances in participating in the gsoc greatly if you could show more of your coding skills :)

**Comment by minad** [comment]
@mohawkjohn It probably means that the maintainer lost interest and only merges bug fixes. But we had issues with the gem (e.g. library lookup) and he suggests rbczmq as successor, so this are enough reasons to switch.

**Comment by liudangyi** [comment]
I've made some commits to my forked repo and when should I send a pull request? After all the related work is done (which may be a lot) or right now?

**Comment by minad** [comment]
You can create a pull request and I can review it in the meantime. We don't have to merge it now. It would be just good to see that you are doing things and that we are working together well.

So in general it would be good if you ask for feedback from time to time.

**Comment by liudangyi** [comment]
I'm not sure how to deal with the Session class.

1. It's created because `ffi-rzmq` requires low-level operations, which is no longer necessary in `rbczmq`.
2. It also does some serialization and unserialization work, which is still needed in `rbczmq`.
3. Besides, it doesn't feel very ruby-like. It's only instantiated once and maybe should be a singleton.

**Comment by minad** [comment]
You are right, the session class is not very good. Can we get rid of it or make it more ruby-like?

**Comment by liudangyi** [comment]
So should we convert it into a module or make it a wrapper of ZMQ::Socket?

**Comment by minad** [comment]
I would prefer a wrapper.
