### ISSUE TITLE
Install kernelspec in jupyter kernel directory

### ISSUE THREAD

**Issue by rgbkrk** [SciRuby/iruby#110]
@kyanny asked in the [nteract slack channel](http://slack.nteract.in) about getting iruby and the  [nteract desktop app](https://github.com/nteract/nteract) working. nteract wasn't detecting the kernel because it's currently installing in the old `.ipython` paths. It would be great if iruby could install into the [jupyter path set](http://jupyter-client.readthedocs.io/en/latest/kernels.html#kernel-specs) for kernels. On our end, we'll likely add in detection for the old paths. In the long term, we definitely want to see kernels use the jupyter kernel directories.

/cc @minrk

**Comment by minrk** [comment]
Yup, that would be great. Using the `jupyter kernelspec install <kernelspec-directory> [--user]` is perhaps the simplest command to do this. The above docs describe the directories to copy to manually if avoiding a dependency on the `jupyter kernelspec` command is desired.

**Comment by kojix2** [comment]
I think so, too.
@mrkn is now working on it!
https://github.com/SciRuby/iruby/pull/171

**Comment by kojix2** [comment]
This issue will be closed when the next version of iruby is released.
Thank you.

**Comment by kojix2** [comment]
I think IRuby 0.3 solves this problem.
If you find any problems, please let us know!
