### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by kozo2** [SciRuby/iruby#114]
This https://github.com/SciRuby/iruby/pull/112 cztop support simplifies iruby installation process.
Can you release the new iruby to rubygems.org?

**Comment by kozo2** [comment]
This cztop support can solve https://github.com/SciRuby/iruby/issues/90 and https://github.com/SciRuby/iruby/issues/80

**Comment by LunarLanding** [comment]
Also, the installation instructions are incompatible with the latest release (0.2.9), since they assume the cztop fix is included.

**Comment by mrkn** [comment]
@v0dro I think this issue can be closed.
