### ISSUE TITLE
Rails app context when using Hydrogen (Atom editor)

### ISSUE THREAD

**Issue by ckib16** [SciRuby/iruby#123]
Hey all,

I'm trying to get [Hydrogen](https://github.com/nteract/hydrogen) to recognize the full "context" of my Rails app.
In other words, be able to call AR queries etc. and have them evaluated
Examples: 
- `Todo.first`
- `Todo.find(19)`

## Goal
Any ideas how to tell Hydrogen/IRuby to evaluate expressions in the context of the full Rails App?
Currently I receive these errors from Hydrogen (inside Atom):

- ![rails context error](https://cloud.githubusercontent.com/assets/2160186/24519886/7104b6d6-1554-11e7-9ad3-a667cd212ad8.png)

## Progress so far
So far I've successfully gotten: 
- IRuby to run as a Jupyter kernel.
- Hydrogen to evaluate simple Ruby expression inside Atom
- ![hydrogen evaluations](https://cloud.githubusercontent.com/assets/2160186/24519600/b024b754-1553-11e7-847e-43f771290c48.png)

## Way Ahead
I saw these two related links in this repo but could not figure out how to implement:
1. https://github.com/SciRuby/iruby/issues/52 - 'Feature request: `rails c`' answered by @ianjepperson
2. https://github.com/wstrinz/jupyter-notebooks/blob/master/Rails%20notebook.ipynb - Example from @wstrinz

I'm happy to document all this for others if someone could help me figure it out.

**Comment by mrkn** [comment]
Is [iruby-rails](https://github.com/mrkn/iruby-rails) helpful for you?

**Comment by ckib16** [comment]
Hi @mrkn - I actually ran into some errors that I didn't know how to fix  - https://github.com/mrkn/iruby-rails/issues/1

But it looks like there is a pull request and a few solutions offered up by other contributors.

I'll take a look and see if I can get it working, thanks got making iruby-rails! :)
