### ISSUE TITLE
Welcome Ruby notebook on try.jupyter.org

### ISSUE THREAD

**Issue by arbox** [SciRuby/iruby#126]
I think we need a welcome notebook on the start page of https://try.jupyter.org/.

Where can we add such one?
UPD: We can provide one here: https://github.com/jupyter/docker-demo-images/tree/master/notebooks

**Comment by v0dro** [comment]
Works. What do you think we should add to the notebook?

**Comment by arbox** [comment]
That's a good question... Other notebooks are rather simplistic. I'd copy the Python notebook and rewrite it since they have good ideas about introductory texts.

**Comment by arbox** [comment]
Snoozing this issue for now, I'll come back to the topic when I have more time, in September or so...

**Comment by jimmynguyc** [comment]
I've made a tutorial from [Ruby in twenty minutes](https://www.ruby-lang.org/en/documentation/quickstart/) and submitted a PR for it https://github.com/jupyter/docker-demo-images/issues/101

**Comment by kojix2** [comment]
[Docker Demo Image repository](https://github.com/jupyter/docker-demo-images) has been archived.
> This repository has been archived by the owner. It is now read-only. 
> This repo is archived and no longer used. If you would like to include a demo of your Jupyter kernel, please add a link to your own demo to the try jupyter page by adding a link, description, and logo [here](https://github.com/jupyter/jupyter.github.io/blob/master/_data/try.yml).

**Comment by arbox** [comment]
The page is now compiled from this Jekyll data bucket: https://github.com/jupyter/jupyter.github.io/blob/master/_data/try.yml

**Comment by kojix2** [comment]
@mrkn recreate RubyData's docker images
https://github.com/RubyData/docker-stacks

**Comment by kojix2** [comment]
I made a pull request to jupyter.github.io.
https://github.com/jupyter/jupyter.github.io/pull/325

**Comment by kojix2** [comment]
@arbox 
Please check this out.  https://jupyter.org/try

![image](https://user-images.githubusercontent.com/5798442/55840031-f2ceb100-5b64-11e9-914c-77855d2e61b7.png)

**Comment by arbox** [comment]
@kojix2 
Nice to see it completed! Thank you all!
