### ISSUE TITLE
Installation instructions for Ubuntu 16.04

### ISSUE THREAD

**Issue by arbox** [SciRuby/iruby#127]
Hi,

I'm working now on a draft for the `IRuby Welcome notebook`  as stated in #126 and I created for me a blank Vagrant scripted VM for the Jupyter installation. During the installation I followed the instructions in the README for Ubuntu `16.04 so I'm wondering:

1. why do we need `cztop` if it is only included for tests in the `Gemfile`;
2. do we really need the newest version of ZeroMQ, no packaged version is sutable?
3. are there any advantages if we use system Ruby?

I can enhance the instructions if I know more :) Thank you!

UPD-01: These details are actually important for the Jupyter Wiki as well: https://github.com/jupyter/jupyter/wiki/Jupyter-kernels
IRuby is not really documented there, we need to improve that.

UPD-02: There is a packaged version of the IRuby kernel under https://launchpad.net/~chronitis/+archive/ubuntu/jupyter/+index

**Comment by v0dro** [comment]
@mrkn can answer this best.

**Comment by mrkn** [comment]
I employed czmq for testing iruby because czmq is now the best zeromq library for ruby.
But, as you mentioned, the package of czmq version 4 isn't provided officially in Ubuntu 16.04.

You can install czmq by apt-get command by following [this instruction](http://software.opensuse.org/download.html?project=home%3Azeromq%3Agit-draft&package=zyre).

**Comment by arbox** [comment]
Thank you @mrkn for the clarification! I'm still lacking some knowledge about the ZeroMQ backend for IRuby.
I assume for some historical reasons first `ffi-zrmq`, than `rbcqmz` and newly `cztop` were used for communication with ZeroMQ. 
Why not stick to `cztop` and use it exclusively? The README offers only this variant, it is installable on every plattform. And it offers a clean way to use a runtime dependency in the Gemspec.

**Comment by mrkn** [comment]
@arbox IMHO the reason is that cztop has appeared recently. 
It's young and depends on both zeromq and cztop >= version 4, that they are latest versions and, their packages are not supported officially many distributions.

I think sticking cztop and dropping rbczmq and ffi-rzmq is good for making future development easy.

**Comment by arbox** [comment]
The only objection from me is that `rbczmq` seems to ship all the external C code, no ZeroMQ parts should be installed separately. If we do not need the functionality which is only available from `cztop` I'd stick with `rbczmq`, not with `cztop`.  But I know to little to judge about that.

**Comment by mrkn** [comment]
@arbox The problem of rbczmq is that its development is inactive.

**Comment by habemus-papadum** [comment]
Hi -- fyi, I just began working with iruby on macosx.   Initially I tried initially with `gem install cztop iruby` -- but the iruby kernel failed to launch even though I had installed zmq via homebrew.   using `gem install rbczmq` took a minute or so to build, but worked fine.  I didn't fully investigate why cztop failed to find my homebrew zmq.

**Comment by mrkn** [comment]
@habemus-papadum Show your error log if you want to investigate your problem.

**Comment by kojix2** [comment]
Readme about installing IRuby is continuously updated.
`cztop` is no longer the first choice, and `ffi-rzmq` is the most recommended library right now.
 If you have an idea to improve the README, please send us pull requests, and someone will merge it. 
Thank you for your effort.
