### ISSUE TITLE
[RFC] Support only cztop (drop rbczmq and ffi-rzmq supports)

### ISSUE THREAD

**Issue by mrkn** [SciRuby/iruby#128]
Following the discussion in #127, dropping rbczmq and ffi-rzmq is good strategy for making the implementation of IRuby more easier.

How do you think about this?  Do you have any objections?

**Comment by arbox** [comment]
See my 5 c in #127 :)

**Comment by v0dro** [comment]
I think this is a good idea. Its a confusing part of the installation for most users.

**Comment by kojix2** [comment]
I agree that we drop only `rbczmq`.
I think dropping rbczmq and ffi-rzmq was a very good idea in May 2017.

But I think it is better to support ffi-rzmq in 2019.

Facts
1. cztop is not very active now. ffi-rzmq is still being updated.
2. cztop stop providing fat gems for windows. One of the biggest benefits of cztop on Windows has been lost.

Speculation

3. Not a few Mac users are using ffi-rzmq.

We have to set environment variables when installing cztop on Mac using homebrew. 
But the document did not explain it until recently.

**Comment by kojix2** [comment]
@mrkn has withdrawn this proposal.

see https://github.com/SciRuby/iruby/issues/163#issuecomment-466732192
> I think ffi-rzmq is best zeromq adapter for all platform now.
> And I reordered adapters at this commit [4db1d99](https://github.com/SciRuby/iruby/commit/4db1d991dc47eaa82bd09ec42fd4614555592f76).

But dropping rbczmq may be discussed in the future.
