### ISSUE TITLE
Better logs

### ISSUE THREAD

**Issue by liudangyi** [SciRuby/iruby#13]
IRuby should use a ruby `Logger` to log rather than directly output to stderr.

My question is, is it necessary to use a [multi-logger](https://github.com/liudangyi/iruby/commit/7ed7ca988fd17ef67908e28897ac3b93097700db#commitcomment-10488056)? The scenarios I can imagine are

1. In development mode, developers need to inspect messages from or to ZMQ.
2. In production mode, users may want to log to a file.

**Comment by minad** [comment]
I would like to have a multilogger to always write to stdout/stderr and optionally to a file. With multilogger you can use different settings for the stdout logger and the file logger. MultiLogger is also pretty simple.

Also please don't overwrite constants in IRuby, like Logger. Use something like

~~~
module IRuby
  class << self
    attr_accessor :logger
  end
end
~~~

**Comment by liudangyi** [comment]
If "logger" is declared as a method, we need to call IRuby.logger rather than directly Logger. 

Maybe we can use LOGGER or something else instead of Logger?

**Comment by minad** [comment]
I think it is okay to call IRuby.logger. If you don't like that you can create an instance method logger in a class which uses IRuby.logger heavily. Abusing constants for that purpose isn't a good idea.

Another suggestion would be to pass :logger option to each class that uses the logger. command creates logger and passes it to kernel for example. What do you think about that?

**Comment by liudangyi** [comment]
I think `IRuby.logger` is better. Passing logger in parameter is not quite necessary because we will always pass the same object every time.
