### ISSUE TITLE
Any support for magics?

### ISSUE THREAD

**Issue by gnilrets** [SciRuby/iruby#130]
I found this GSOC project from a few years ago that indicated some work was being on supporting magics in iRuby.  Was this actually implemented in any way?  I tried `%lsmagic` but just got an error `SyntaxError: <main>: unterminated string meets end of file`

**Comment by v0dro** [comment]
I don't think magic commands exist as of now. I think @mrkn was working on it.

**Comment by kojix2** [comment]
#140

**Comment by kojix2** [comment]
Hello.
We are sorry, but we do not plan to support magic.
https://github.com/SciRuby/iruby/pull/140#issuecomment-529923243
