### ISSUE TITLE
Install `libzmq3-dev` instead of `libzmq-dev` on Ubuntu 17.04

### ISSUE THREAD

**Issue by chezou** [SciRuby/iruby#131]
I succeeded installation iRuby on Ubuntu 17.04 smoothly, except for one caveat.

Per README, Ubuntu 16.04 requires `libzmq-dev`. But, Ubuntu 17.04 no longer provides the package [`libzmq-dev`](https://packages.ubuntu.com/search?keywords=libzmq-dev); we should use `libzmq3-dev` instead.

```
sudo apt install libzmq3-dev
```

Then, we can install iRuby on Ubuntu 17.04.

**Comment by mrkn** [comment]
I've changed the description for Ubuntu by adding 17.04-specific explanations.
Check it, please.
