### ISSUE TITLE
iruby InteractiveShell

### ISSUE THREAD

**Issue by wta12** [SciRuby/iruby#135]
```
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
```
Have any equivalence of above code for iruby in jupyter when i want to see all output without print statement like in python ?

**Comment by mrkn** [comment]
Nothing.

**Comment by mrkn** [comment]
Your contribution is welcome.

**Comment by kojix2** [comment]
InteractiveShell is an interesting feature. 
But, we have no plans to implement the feature at this time. 
Of course pull requests are always welcome. 
This issue is not active, so I close it.
Thank you.
