### ISSUE TITLE
RuntimeError occurred on console just after executing code

### ISSUE THREAD

**Issue by mrkn** [SciRuby/iruby#145]
When I run `RUBY_VERSION` in the code cell on iruby console, the following RuntimeError occurred.

I think we respond something in `is_complete_request` message because jupyter_console said: `UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.`

```
In [1]: RUBY_VERSION/Users/mrkn/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/jupyter_console/ptshell.py:617: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
  warn('The kernel did not respond to an is_complete_request. '
In [1]: RUBY_VERSION
RuntimeError: Unknown message type: {:idents=>["fa4a0dcb-2dd13f430daf4cb7079d128f"], :header=>{"version"=>"5.3", "date"=>"2018-03-23T02:35:04.485597Z", "session"=>"fa4a0dcb-2dd13f430daf4cb7079d128f", "username"=>"mrkn", "msg_type"=>"is_complete_request", "msg_id"=>"eba9cfeb-3fadb1ced795c0276f4bae89"}, :parent_header=>{}, :metadata=>{}, :content=>{"code"=>"RUBY_VERSION"}, :buffers=>nil}
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iruby-0.3/lib/iruby/kernel.rb:44:in `dispatch'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iruby-0.3/lib/iruby/kernel.rb:37:in `run'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iruby-0.3/lib/iruby/command.rb:70:in `run_kernel'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
/Users/mrkn/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
/Users/mrkn/.rbenv/versions/2.5/bin/iruby:23:in `load'
/Users/mrkn/.rbenv/versions/2.5/bin/iruby:23:in `<main>'
Out[1]: "2.5.0"
```

**Comment by kojix2** [comment]
I also tried it. No error occurred.

* Ubuntu 18.10
* Ruby 2.6.1 rbenv
* no Gemfile (So I got no gem file error)
* IRuby 0.3 (github master)

**Comment by kojix2** [comment]
I have checked the behavior of IRuby on Mac OS X

> ProductName:	Mac OS X
> ProductVersion:	10.14.6

jupyter version 4.4.0
jupyter console version 6.0.0

Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
IRuby : Github master https://github.com/SciRuby/iruby/commit/8e8b58d50590fd739d3b4ca46c0e01fd1af0cdab
adapter : ffi-rzmq

The error is not reproduced. Maybe this problem has been solved. 
So I will close this issue. 

Please feel free to reopen if you have any problems. 
Thank you.
