### ISSUE TITLE
Kernel died since do not load mimemagic, which exists

### ISSUE THREAD

**Issue by flavono123** [SciRuby/iruby#149]
I've got followed error when I clicked the file with iruby kernel:
```sh
$ # in local dir with Gemfile
$ jupyter notebook
FATAL -- : Kernel died: cannot load such file -- mimemagic
/Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby.rb:1:in `require'
/Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby.rb:1:in `<top (required)>'
/Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/command.rb:69:in `require'
/Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/command.rb:69:in `run_kernel'
/Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
/Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
/Users/hong/.rbenv/versions/2.4.3/bin/iruby:23:in `load'
/Users/hong/.rbenv/versions/2.4.3/bin/iruby:23:in `<main>'
/Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby.rb:1:in `require': cannot load such file -- mimemagic (LoadError)
	from /Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby.rb:1:in `<top (required)>'
	from /Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/command.rb:69:in `require'
	from /Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/command.rb:69:in `run_kernel'
	from /Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
	from /Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
	from /Users/hong/.rbenv/versions/2.4.3/bin/iruby:23:in `load'
	from /Users/hong/.rbenv/versions/2.4.3/bin/iruby:23:in `<main>'
```

Seemed above message, I use ruby version 2.4.3  with `rbenv` in highsierra 10.13.3(17D47).
And `mimemagic` is installed in local:
```sh
$ bundle show mimemagic
/Users/hong/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/mimemagic-0.3.2
```
The part of Gemfile related with is:
```ruby
...
group :iruby do
  gem 'iruby'
end
...
```
How could I run the kernel?

**Comment by mrkn** [comment]
Show the code that you were writing in code cells.

**Comment by flavono123** [comment]
No codes in a cell, it triggered when just creating or opening the file with iruby kernel.

**Comment by designium** [comment]
It also happens to my installation, sometime it shows up and sometimes it doesn't .

**Comment by kojix2** [comment]
Hi @designium
Thank you for your new report about IRuby and mimemagic. 

If you don't mind, could you tell me more about your environment?

**Comment by designium** [comment]
BTW, I commented out the "gem 'mimemagic' and it worked again. But it's strange because it was working before the update of my brew and bundle update.

Sure, here you go:

- macOS Version 10.14.6
- Python 3.7.0
- pip 19.3.1 from /Users/[********]/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip (python 3.7)
- I use pyenv

Gemfile.lock

GEM
        remote: https://rubygems.org/
        specs:
          activemodel (6.0.1)
            activesupport (= 6.0.1)
          activerecord (6.0.1)
            activemodel (= 6.0.1)
            activesupport (= 6.0.1)
          activesupport (6.0.1)
            concurrent-ruby (~> 1.0, >= 1.0.2)
            i18n (>= 0.7, < 2)
            minitest (~> 5.1)
            tzinfo (~> 1.1)
            zeitwerk (~> 2.2)
          addressable (2.7.0)
            public_suffix (>= 2.0.2, < 5.0)
          akami (1.3.1)
            gyoku (>= 0.4.0)
            nokogiri
          ast (2.4.0)
          axiom-types (0.1.1)
            descendants_tracker (~> 0.0.4)
            ice_nine (~> 0.11.0)
            thread_safe (~> 0.3, >= 0.3.1)
          bond (0.5.1)
          builder (3.2.3)
          capybara (3.29.0)
            addressable
            mini_mime (>= 0.1.3)
            nokogiri (~> 1.8)
            rack (>= 1.6.0)
            rack-test (>= 0.6.3)
            regexp_parser (~> 1.5)
            xpath (~> 3.2)
          childprocess (3.0.0)
          chronic (0.10.2)
          cli-ui (1.3.0)
          cliver (0.3.2)
          codeclimate-engine-rb (0.4.1)
            virtus (~> 1.0)
          coercible (1.0.0)
            descendants_tracker (~> 0.0.1)
          colorize (0.8.1)
          concurrent-ruby (1.1.5)
          connection_pool (2.2.2)
          csv (3.1.2)
          czmq-ffi-gen (0.16.1)
            ffi (~> 1.11)
          cztop (0.14.1)
            czmq-ffi-gen (~> 0.16)
          data_uri (0.1.0)
          descendants_tracker (0.0.4)
            thread_safe (~> 0.3, >= 0.3.1)
          diff-lcs (1.3)
          domain_name (0.5.20190701)
            unf (>= 0.0.5, < 1.0.0)
          dotenv (2.7.5)
          equalizer (0.0.11)
          ffi (1.11.3)
          geocoder (1.5.2)
          gyoku (1.3.1)
            builder (>= 2.1.2)
          http-accept (1.7.0)
          http-cookie (1.0.3)
            domain_name (~> 0.5)
          httpi (2.4.4)
            rack
            socksify
          i18n (1.7.0)
            concurrent-ruby (~> 1.0)
          ice_nine (0.11.2)
          iruby (0.4.0)
            bond (~> 0.5)
            data_uri (~> 0.1)
            mimemagic (~> 0.3)
            multi_json (~> 1.11)
          jaro_winkler (1.5.4)
          json (2.2.0)
          kwalify (0.7.2)
          mail (2.7.1)
            mini_mime (>= 0.1.1)
          mechanize (2.7.6)
            domain_name (~> 0.5, >= 0.5.1)
            http-cookie (~> 1.0)
            mime-types (>= 1.17.2)
            net-http-digest_auth (~> 1.1, >= 1.1.1)
            net-http-persistent (>= 2.5.2)
            nokogiri (~> 1.6)
            ntlm-http (~> 0.1, >= 0.1.1)
            webrobots (>= 0.0.9, < 0.2)
          mime-types (3.3)
            mime-types-data (~> 3.2015)
          mime-types-data (3.2019.1009)
          mimemagic (0.3.3)
          mini_mime (1.0.2)
          mini_portile2 (2.4.0)
          minitest (5.13.0)
          multi_json (1.14.1)
          net-http-digest_auth (1.4.1)
          net-http-persistent (3.1.0)
            connection_pool (~> 2.2)
          net-ssh (5.2.0)
          net-ssh-gateway (2.0.0)
            net-ssh (>= 4.0.0)
          netrc (0.11.0)
          nokogiri (1.10.5)
            mini_portile2 (~> 2.4.0)
          nori (2.6.0)
          ntlm-http (0.1.1)
          parallel (1.19.1)
          parser (2.6.5.0)
            ast (~> 2.4.0)
          pg (1.1.4)
          poltergeist (1.18.1)
            capybara (>= 2.1, < 4)
            cliver (~> 0.3.1)
            websocket-driver (>= 0.2.0)
          progressbar (1.10.1)
          psych (3.1.0)
          public_suffix (4.0.1)
          rack (2.0.7)
          rack-test (1.1.0)
            rack (>= 1.0, < 3)
          rainbow (3.0.0)
          rake (13.0.1)
          reek (5.5.0)
            codeclimate-engine-rb (~> 0.4.0)
            kwalify (~> 0.7.0)
            parser (>= 2.5.0.0, < 2.7, != 2.5.1.1)
            psych (~> 3.1.0)
            rainbow (>= 2.0, < 4.0)
          regexp_parser (1.6.0)
          rest-client (2.1.0)
            http-accept (>= 1.7.0, < 2.0)
            http-cookie (>= 1.0.2, < 2.0)
            mime-types (>= 1.16, < 4.0)
            netrc (~> 0.8)
          roo (2.8.2)
            nokogiri (~> 1)
            rubyzip (>= 1.2.1, < 2.0.0)
          rspec (3.9.0)
            rspec-core (~> 3.9.0)
            rspec-expectations (~> 3.9.0)
            rspec-mocks (~> 3.9.0)
          rspec-core (3.9.0)
            rspec-support (~> 3.9.0)
          rspec-expectations (3.9.0)
            diff-lcs (>= 1.2.0, < 2.0)
            rspec-support (~> 3.9.0)
          rspec-mocks (3.9.0)
            diff-lcs (>= 1.2.0, < 2.0)
            rspec-support (~> 3.9.0)
          rspec-support (3.9.0)
          rubocop (0.76.0)
            jaro_winkler (~> 1.5.1)
            parallel (~> 1.10)
            parser (>= 2.6)
            rainbow (>= 2.2.2, < 4.0)
            ruby-progressbar (~> 1.7)
            unicode-display_width (>= 1.4.0, < 1.7)
          ruby-progressbar (1.10.1)
          rubyzip (1.3.0)
          savon (2.12.0)
            akami (~> 1.2)
            builder (>= 2.1.2)
            gyoku (~> 1.2)
            httpi (~> 2.3)
            nokogiri (>= 1.8.1)
            nori (~> 2.4)
            wasabi (~> 3.4)
          selenium-webdriver (3.142.6)
            childprocess (>= 0.5, < 4.0)
            rubyzip (>= 1.2.2)
          socksify (1.7.1)
          sqlite3 (1.4.1)
          thread_safe (0.3.6)
          tiny_tds (2.1.2)
          tzinfo (1.2.5)
            thread_safe (~> 0.1)
          unf (0.1.4)
            unf_ext
          unf_ext (0.0.7.6)
          unicode-display_width (1.6.0)
          virtus (1.0.5)
            axiom-types (~> 0.1)
            coercible (~> 1.0)
            descendants_tracker (~> 0.0, >= 0.0.3)
            equalizer (~> 0.0, >= 0.0.9)
          wasabi (3.5.0)
            httpi (~> 2.0)
            nokogiri (>= 1.4.2)
          watir (6.16.5)
            regexp_parser (~> 1.2)
            selenium-webdriver (~> 3.6)
          watir-nokogiri (1.0.0)
            nokogiri
          webdrivers (4.1.3)
            nokogiri (~> 1.6)
            rubyzip (>= 1.3.0)
            selenium-webdriver (>= 3.0, < 4.0)
          webrobots (0.1.2)
          websocket-driver (0.7.1)
            websocket-extensions (>= 0.1.0)
          websocket-extensions (0.1.4)
          whenever (1.0.0)
            chronic (>= 0.6.3)
          xpath (3.2.0)
            nokogiri (~> 1.8)
          zeitwerk (2.2.1)

      PLATFORMS
        ruby

      DEPENDENCIES
        activerecord
        activerecord-jdbcsqlite3-adapter
        activesupport
        bundler
        cli-ui
        colorize
        csv
        cztop
        dotenv
        geocoder
        iruby
        json
        mail
        mechanize
        net-ssh
        net-ssh-gateway
        parallel
        pg
        poltergeist
        progressbar
        rake
        reek
        rest-client
        roo
        rspec
        rubocop
        ruby-progressbar
        savon
        sqlite3
        tiny_tds
        watir
        watir-nokogiri
        webdrivers (~> 4.0)
        whenever

      BUNDLED WITH
         1.17.2

**Comment by kojix2** [comment]
IRuby has discontinued the use of mimemagic due to licensing issues. It is not clear whether the cause of this problem has been resolved, but the same error message should not appear anymore, so the issue is closed.

https://github.com/SciRuby/iruby/pull/291
