### ISSUE TITLE
IRuby not starting control_port

### ISSUE THREAD

**Issue by matugm** [SciRuby/iruby#150]
Hi,
I'm trying to use [Atom's Hydrogen](https://atom.io/packages/hydrogen) plugin.

It's not working & I tracked it down to the `control_port` not being open.

Using [Wireshark](https://en.wikipedia.org/wiki/Wireshark) you can see how Hydrogen keeps trying to connect to the `control_port`, but since it's not open then it doesn't work.

The plugin runs iruby like this:

```
iruby kernel /run/user/1000/jupyter/kernel-1668f7b9-c2c3-431b-99cb-2acabe4a00de.json
```

Where the json file contains:

```json
{
  "version": 5,
  "key": "9b96aefa-77ba-4ac3-9178-2f13872ffe5e",
  "signature_scheme": "hmac-sha256",
  "transport": "tcp",
  "ip": "127.0.0.1",
  "hb_port": 9000,
  "control_port": 9001,
  "shell_port": 9002,
  "stdin_port": 9003,
  "iopub_port": 9004
}
```

Checking with `netstat`, all ports are open but 9001. Changing the port number to something else doesn't help.

Ruby Version:
* Ruby 2.5.0

Gems:

* czmq-ffi-gen (0.15.0)
* cztop (0.13.1)
* iruby (0.3)

It would be nice if we can get this to work :)

Any ideas?

**Comment by kojix2** [comment]
Hello @matugm.

IRuby doesn't have a control port yet.
#185
