### ISSUE TITLE
Jupyter Lab Plotly Support

### ISSUE THREAD

**Issue by zach-capalbo** [SciRuby/iruby#154]
I was playing around with `iruby` in order to get it work with the [Jupyter Lab Plotly Extension](https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension)

It doesn't require much change; I've come up with a quick monkey patch:

```ruby
module IRuby
  module Display
    class << self
      def protect(mime, data)
        return data if mime == 'application/vnd.plotly.v1+json'
        MimeMagic.new(mime).text? ? data.to_s : [data.to_s].pack('m0')
      end
    end
  end

  def self.plot(data, layout = {})
    IRuby.convert({data: data, layout: layout}, mime: "application/vnd.plotly.v1+json")
  end
end
```

![image](https://user-images.githubusercontent.com/1325621/42135907-0ab61fd4-7d20-11e8-8b74-8c772e5b5c2d.png)

If I make a pull request with these changes, would this be something worth incorporating into iruby? Or would it be better as a separate gem.

Thanks!

**Comment by homonecloco** [comment]
I was about to look for a way to do this. I think this would be a nice addition

**Comment by kojix2** [comment]
Hello @zach-capalbo
It looks Great !

[Jupyter renderer](https://github.com/jupyterlab/jupyter-renderers) supports several mime types. 
* application/vnd.fasta.fasta
* application/geo+json
* **application/vnd.plotly.v1+json**
* application/vnd.vega.v2+json
* application/vnd.vegalite.v1+json
* application/vnd.vega.v3+json
* application/vnd.vegalite.v2+json

I think IRuby should supports these MIME types.

```ruby
return data if mime == 'application/vnd.plotly.v1+json'
```

**Comment by mrkn** [comment]
I don't want to let iruby depend on the specific plotting library.

You can make a gem to provide such a feature.

**Comment by kojix2** [comment]
IJulia seems to support these MIME types. 

https://github.com/JuliaLang/IJulia.jl/commit/aca8d5ba363597ec25969c5b10f05d1f06fb721a
https://github.com/JuliaLang/IJulia.jl/commit/4fb2a4698e36701185dcfcfac000595182a1f729

Would you please think about it again?

**Comment by mrkn** [comment]
I meant that I don’t want to introduce the method like `IRuby.plot` for the specific plotting library.
The reason why I don’t want to introduce plotting feature in IRuby is  that there is no standard plotting libraries for Ruby.

I think we don’t need to change the code for supporting the new MIME types.  Please look [display.rb](https://github.com/SciRuby/iruby/blob/master/lib/iruby/display.rb).

If you feel that I didn’t understand your proposal rightly, would you please describe what you want to do more concretely.

**Comment by kojix2** [comment]
@mrkn 
I don't want to introduce `IRuby.plot`either. 

Plotly dose not work because IRuby will pack objects with unknow mime type`.

```ruby
data = IRuby::Display.display(
    {data: [{y:[*1..5].shuffle}],layout:{}},
    mime: 'application/vnd.plotly.v1+json'
    )
ap data
```
![image](https://user-images.githubusercontent.com/5798442/57570052-c09cc180-7438-11e9-92cc-ca16e33a82a9.png)

To avoid packing, you need to avoid the `protect` method, as @zach-capalbo wrote in the monkey patch.

```ruby
module IRuby
  module Display
    class << self
      def protect(mime, data)
        return data if mime == 'application/vnd.plotly.v1+json'
        MimeMagic.new(mime).text? ? data.to_s : [data.to_s].pack('m0')
      end
    end
  end
end
```

then, 

```ruby
data = IRuby::Display.display(
    {data: [{y:[*1..5].shuffle}],layout:{}},
    mime: 'application/vnd.plotly.v1+json'
    )
ap data
```

![image](https://user-images.githubusercontent.com/5798442/57570263-0490c600-743b-11e9-9afe-cacf3e7ced02.png)

So we might have to register these mime types in code  to avoid packing?

**Comment by zach-capalbo** [comment]
For what it's worth, Ruby itself also doesn't support LaTex, PNG, SVG, etc, but these are all passed through to Jupyter and supported by IRuby.

In any case, I've just created the [`iruby-plotly` gem.](https://rubygems.org/gems/iruby-plotly) (https://github.com/zach-capalbo/iruby-plotly). 

If you decide to allow plotting in the IRuby core, I can update & deprecate the gem later.

**Comment by kojix2** [comment]
（´-`）.｡oO (I just found [Flammarion](https://github.com/zach-capalbo/flammarion). It's cool!)

**Comment by kojix2** [comment]
IRuby-plotly is not famous but very useful.
It may be included in the README.
