### ISSUE TITLE
how to add ruby kernel on centos?

### ISSUE THREAD

**Issue by fakeYanss** [SciRuby/iruby#155]
I see the way to add ruby kernel on ubantu. But my centos use yum. So how i can do it on centos 6?

**Comment by kojix2** [comment]
Hello. 
Please write how you tried.

**Comment by fakeYanss** [comment]
I have solved it on centos.
First, install ruby and other tools,
```
sudo yum install -y git-core ruby-devel ruby zlib zlib-devel gcc-c++ patch readline readline-devel libyaml-devel libffi-devel openssl-devel make
```
Second, install ZeroMQ,
```
sudo yum install zeromq-devel zeromq czmq
gem install cztop rbczmq ffi_rzmq
```
At Last, install iruby kernel,
```
gem install cztop iruby
iruby register --force
```

**Comment by kojix2** [comment]
@fakeYanss 
We're happy to see people coming to SciRuby community. 
Thanks you for your reply!
