### ISSUE TITLE
Kernel error in Python3.4.3 and IPython Notebook3.1.0

### ISSUE THREAD

**Issue by kozo2** [SciRuby/iruby#16]
There was a Kernel error on

- iruby commit 4e37c78e33e26d9745b95f44306a41c2f21718ec
- Python 3.4.3 32bit (downloaded from www.python.org)
- IPython 3.1.0 (installed with pip install)

I uploaded the log to

https://gist.github.com/kozo2/1b2799a45381f911089f

**Comment by minad** [comment]
Can you test again with the newest version? I am not using windows :-/

Any windows users here who could help?
