### ISSUE TITLE
(Windows ) Trouble installing iruby (Ruby 2.6)

### ISSUE THREAD

**Issue by kojix2** [SciRuby/iruby#163]
I can not install iruby on WIndows 10 with Ruby 2.6.0.1 (ruby installer)
cztop is dependent on czmq-ffi-gen. 

Here is the czmq-ffi-gen.gemspec
> spec.add_runtime_dependency "ffi", "~> 1.9.10"

ffi 1.9.10 seems to be obsolete.
I rewrote gemspec and installed it and latest ffi. The installation of iruby ended successfully, but it did not work. 

I do not investigate this problem any further today.

Is anyone using iruby on Windows 10 ＆ Ruby 2.6?

**Comment by kojix2** [comment]
I could run IRuby on Windows 10.
1. install zeromq (MSYS2 Pacman)
2. uninstall cztop, czmq-ffi-gen
3. install ffi-rzmq

cztop is not in good shape. Maybe ffi-rzmq is good for Windows right now. 
https://gitlab.com/paddor/cztop/issues/17

**Comment by kojix2** [comment]
https://github.com/SciRuby/iruby/issues/148

**Comment by mrkn** [comment]
I think ffi-rzmq is best zeromq adapter for all platform now.
And I reorder adapters at this commit https://github.com/SciRuby/iruby/commit/4db1d991dc47eaa82bd09ec42fd4614555592f76.
