### ISSUE TITLE
Ability for code to detect if running in iruby

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#18]
Will it possible to define some sort of a constant or something similar that will let a ruby script query if it is running in the iruby browser environment?

This will allow optionally running code that will fancifully print stuff in iruby format (HTML) only when it is running in the iruby browser environment, and something else when running in the console (irb, pry,etc.).

To demonstrate:

``` ruby

if RUNNING_IN_IRUBY_BROWSER
  print "<h1>This is in iruby<h1>"
else
  print "This is in console"
end

```

**Comment by minad** [comment]
I am not sure if there is a possibility provided by ipython. I think it would be a good idea to add an api for that.

~~~
IRuby.mode = nil, :console, :notebook, :qtconsole, ...
IRuby.notebook?
~~~

**Comment by v0dro** [comment]
Yeah I'm also thinking something on those lines.

**Comment by minad** [comment]
This is not a good idea and it is by design for the backend not to know the frontend. Use IRuby.display with different mimetypes if you want't to achieve something specific.

See http://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook

**Comment by ankane** [comment]
I've found myself wanting to do a similar thing fwiw - show an IRuby table if its IRuby and a text table otherwise. A hacky way to do this is:

```ruby
$0.end_with?("iruby")
```
