### ISSUE TITLE
Improve array and matrix display speed

### ISSUE THREAD

**Issue by kojix2** [SciRuby/iruby#197]
It may be time to rethink how iRuby displays arrays.

Matrix rendering with MathJax is beautiful. However, it is not appropriate when displaying large sized arrays or matrices. In the worst case, the browser freezes.

https://github.com/ruby-numo/numo-narray/issues/124

**Comment by kojix2** [comment]
@zalt50 What do you think?

**Comment by prasunanand** [comment]
Cc @uditgulati

**Comment by zalt50** [comment]
How about c5bcfdc516b2cc2fc9a9d76e42eb44590fd799d1?

**Comment by kojix2** [comment]
I see.
I think it's very good.
I want to display the last number of each line if possible.

**Comment by mrkn** [comment]
I want to stop implicitly use of MathJax for displaying the result.

**Comment by kojix2** [comment]
@prasunanand
Thank you .I am a fan of NArray. 
Let me know if you have any feedback from NMatrix community.

@mrkn
I agree. But I want to improve the usability right now.

@zalt50 How about https://github.com/kojix2/iruby/commit/b3f7ddc662442669b9b9ef5dbf29e5eb70bc0293

![image](https://user-images.githubusercontent.com/5798442/56874136-dabac500-6a72-11e9-9573-a159a5fb7a99.png)

**Comment by Uditgulati** [comment]
I think only showing first 5 and last rows and columns should be enough.

We are thinking of fixing this problem for NMatrix too during this GSoC.

**Comment by zalt50** [comment]
https://github.com/kojix2/iruby/commit/b3f7ddc662442669b9b9ef5dbf29e5eb70bc0293 is nice for me, but some people don't need MathJax so is it possible to choose whether to use MathJax in the execution environment?

**Comment by kojix2** [comment]
Oops, It was discussed in the past #97

**Comment by kojix2** [comment]
Changed default display format for NArray to text/plain.
Thanks to everyone who commented.
