### ISSUE TITLE
Can I use it to parse .ipynb files into html?

### ISSUE THREAD

**Issue by SURA907** [SciRuby/iruby#204]
Can I use it to parse .ipynb files into html?
and the method in doc?
thanks

**Comment by kojix2** [comment]
Hello @SURA907 

You can export notebooks as html from browser.

### Jupyter Notebook
![image](https://user-images.githubusercontent.com/5798442/59402122-1f5aaf80-8dd8-11e9-8f7b-03c1b83fceaf.png)

### Jupyter Lab
![image](https://user-images.githubusercontent.com/5798442/59402018-c4c15380-8dd7-11e9-8ad5-5b231467558d.png)

### Command line tool
use `jupyter nbconvert`
```bash
jupyter nbconvert --to html notebook.ipynb
```
Chinese document I found by baidu search
[如何将ipynb转换为html，md，pdf等格式](https://blog.csdn.net/red_stone1/article/details/73380517)

### RDoc / Yard
You mean you want to generate RDoc or Yard documentation from ipynb?
I don't know a good way to do that. You may have to export ipynb as rb file once.

**Comment by SURA907** [comment]
- I used the front-end library notebookjs to parse the .ipynb file into html format.
- Because .ipynb contains text in markdown format internally, and the company stipulates that the parser maintained by the company must be used to parse markdown.
- so I have to parse markdown on the backend, and the rest are parsed in the front end.
- I might take the time to do a ruby implementation of nodebookjs.

**Comment by kojix2** [comment]
I see.

So you were looking for an ipynb parser implemented in Ruby.
IRuby is a Jupyter kernel, not a parser. 
Unfortunately, you can't use it for that purpose.

**Comment by SURA907** [comment]
Thank you for your answer
