### ISSUE TITLE
Callstacks render with white foreground

### ISSUE THREAD

**Issue by thomasjm** [SciRuby/iruby#208]
Here's an example of what I mean:

![image](https://user-images.githubusercontent.com/1634990/61423147-8e3d9380-a8c3-11e9-814b-46023f75ead6.png)

The output returned from IRuby uses the ANSI color code for "white foreground" to render most of the callstack.

Jupyter notebook renders this using a color that is *barely* visible, but it's still a little hard to read. Is there a way to make it use darker colors when they're going to be rendered on a light background?

**Comment by kojix2** [comment]
Thank you @thomasjm for your report.

I don't think this is what you really want, but try it if you like.

```ruby
IRuby::Kernel::WHITE = "\e[32m" # green
```

![image](https://user-images.githubusercontent.com/5798442/61430415-c812a680-a964-11e9-8f80-eb63c872cfb2.png)

**Comment by thomasjm** [comment]
Thanks for that @kojix2 -- now I can see where this is happening: https://github.com/SciRuby/iruby/blob/da5663205a64f984815700146862e95dfab62764/lib/iruby/kernel.rb#L109

My question is, is this really such a good idea? If you look at other Jupyter kernels such as IPython, most text is not decorated. (With the exception of certain keywords that are red or green or blue, which works on either light or dark backgrounds.) This allows the terminal/notebook/whatever to use its default font color, which looks good for most text. 

For example, here's an IPython stacktrace rendered in my console and also in the notebook:

![image](https://user-images.githubusercontent.com/1634990/61436746-4da83f00-a8f0-11e9-845f-d8f52a73a27c.png)

![image](https://user-images.githubusercontent.com/1634990/61436797-67498680-a8f0-11e9-87c8-9c0253c2f58b.png)

What do you think of just removing this white highlighting?

**Comment by kojix2** [comment]
That sounds reasonable.

But you see most of the error messages are about `pry`. 
The message about your code is just a few lines. 
I think that's why the error messages are white and hard to see in IRuby.

So I think we should remove the white tag from the error message and fix #142.

The problem is that no one solves # 142 for a long time.

**Comment by kojix2** [comment]
You are using irb backend, not Pry. I'm sorry.

**Comment by thomasjm** [comment]
Hmm, it sounds like they are two separate problems: 1) overly-long tracebacks and 2) hard-to-read tracebacks. I don't think we need a fix for #142 to fix the second problem immediately, right?

**Comment by kojix2** [comment]
ping @mrkn 
Do you want to remove the white ANSI escape code?

**Comment by mrkn** [comment]
I think we should follow Exception#full_message feature.

**Comment by kojix2** [comment]
@mrkn
So you mean we can remove the white escape character right?

@thomasjm 
If you don't mind, could you send me a pull request to remove WHITE escape character?

**Comment by thomasjm** [comment]
Thanks @kojix2 -- just sent a PR. Please see my note there about a possible issue on `master` branch at the moment.

On a related note, would it be possible to get a new release on Github and Rubygems? The last Github release was `0.2.9` in 2016, and the last Rubygems release was `0.3.0` in 2017.

**Comment by thomasjm** [comment]
Closing this issue now, thanks @kojix2 !

By the way, what do you think of my request above for cutting a new release?
