### ISSUE TITLE
Releasing a new version of gem

### ISSUE THREAD

**Issue by mrkn** [SciRuby/iruby#211]
I'd like to release a new version of iruby.gem.

@v0dro Could you build and push a new version of iruby.gem to rubygems.org?
Or, could you please add me to owner of iruby.gem on rubygems.org?

**Comment by v0dro** [comment]
OK. I'll add you as the owner.

**Comment by v0dro** [comment]
Which email ID should I associate with rubygems?

**Comment by mrkn** [comment]
@v0dro Please add `mrkn AT mrkn.jp`

**Comment by v0dro** [comment]
I have added you as an owner. https://rubygems.org/gems/iruby

**Comment by mrkn** [comment]
@v0dro Thank you!
