### ISSUE TITLE
Does pyzmq_adapter need some additional files to work?

### ISSUE THREAD

**Issue by kojix2** [SciRuby/iruby#218]
@mrkn
Hello. I have a question.
I think pyzmq_adapter need some files that dose not added to the Github repository. 
Is that right?

https://github.com/SciRuby/iruby/blob/8e8b58d50590fd739d3b4ca46c0e01fd1af0cdab/lib/iruby/session_adapter/pyzmq_adapter.rb#L28-L29

**Comment by mrkn** [comment]
Oops.  Yes, it is. I forgot to add and commit a file for python side, and I lost it.

Anyway, pyzmq adapter is not completed, I must disable it.

**Comment by kojix2** [comment]
Thanks. I got it!
