### ISSUE TITLE
Implement stdin

### ISSUE THREAD

**Issue by minad** [SciRuby/iruby#24]

**Comment by TI-Admin** [comment]
Is iruby still under support and is there a chance that 'gets' will be working someday ?

**Comment by kylekyle** [comment]
Have you taken a look at [Ruby::Input](https://github.com/SciRuby/iruby/blob/master/lib/iruby/input/README.ipynb)?

**Comment by TI-Admin** [comment]
Yes, I know about that. We want to use iruby for teaching at the university, therefore we do need the vanilla ruby classes working. Is there a specific reason gets is not supported ? If you can give a hint perhaps it is fixable by our students.

**Comment by v0dro** [comment]
Hmmm supporting STDIN would be interesting. @mrkn do you know how to do this?

Here's a lead: https://github.com/ipython/ipython/pull/3089
http://stackoverflow.com/questions/18490447/manage-stdout-and-stdin-in-ipython-notebook

**Comment by v0dro** [comment]
Has this been implemented?
