### ISSUE TITLE
Different install dir for iruby-kernel

### ISSUE THREAD

**Issue by gtom** [SciRuby/iruby#242]
Maybe I missed something, but I'm not able to install iruby-Kernel into a different directory:
`gem install iruby --pre`
installs iruby-kernel in `/home/user/.local/share/jupyter/kernels/ruby`
but I like to install it into a global accessible subdir (e.g. /opt/....).
I did not find any documentation doing this, but I found this issue ([https://github.com/SciRuby/iruby/pull/171](https://github.com/SciRuby/iruby/pull/171)). Does anybody know, how to do this in a way like
`sudo gem install iruby --pre --prefix='/opt/mykernels/'`

Thanks in advance
gTom

**Comment by kojix2** [comment]
Hello. gtom

Please use the juypter kernelspec command.

`jupyter kernelspec install /home/user/.local/share/jupyter/kernels/ruby --prefix=your/dir/ruby`

For example,
```
jupyter kernelspec install ~/Documents/ruby/kernels/ruby/ --prefix="~/Download/"
```
But this command just copy your kernelspec directory, and perhaps you might get some warnings like

```
[InstallKernelSpec] WARNING | Installing to /home/kojix2/Download/share/jupyter/kernels, which is not in ['/home/kojix2/.local/share/jupyter/kernels', '/home/kojix2/anaconda3/share/jupyter/kernels', '/usr/local/share/jupyter/kernels', '/usr/share/jupyter/kernels', '/home/kojix2/.ipython/kernels']. The kernelspec may not be found.
[InstallKernelSpec] Installed kernelspec ruby in /home/kojix2/Download/share/jupyter/kernels/ruby
```

In that case, you run `jupyter kernelspec list` to see if iruby is registered or not. `jupyter --path`  show the directories where jupyter look for the kernelspec. You can define the environment variable `JUPYTER_DATA_DIR` or `JUPYTER_PATH` to set the user data directory.

* https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html
* https://github.com/jupyter/jupyter/issues/449

In fact, `iruby register` command also checks the environment variable `JUPYTER_DATA_DIR` and it places the kernel spec directory there. But the `jupyter kernelspec` command may be more reliable.

**Comment by gtom** [comment]
Thanks kojix2, your excellent description helped a lot. After `kernelspec install` everythink works as aspected, the iruby-kernel is loaded from /opt/-path. If I display a new 
`jupyter kernelspec list`
command, it still shows me the old path for iruby-kernel (/home/user...), but this seems to be no problem.
So I close this issue.
Thanks again for fast help.
gTom
