### ISSUE TITLE
Shortcut for accessing previous output; the variable _ dose not work

### ISSUE THREAD

**Issue by kojix2** [SciRuby/iruby#245]
Found by @Yuki-Inoue 
> Is it possible to obtain last evaluated value in iruby on jupyter?
>
> I use iruby on jupyter. In ipython, one can obtain last evaluated value by local variable _. Is it possible to do somehow achieve it in iruby?

https://stackoverflow.com/questions/54512493/is-it-possible-to-obtain-last-evaluated-value-in-iruby-on-jupyter/57925952#57925952

**Comment by ankane** [comment]
Hey @kojix2, were you able to confirm it's an issue? It seems to be working with the latest version.

<img width="201" alt="Screen Shot 2021-01-02 at 4 31 58 PM" src="https://user-images.githubusercontent.com/220358/103469320-0c8c3080-4d18-11eb-9680-2496e5796452.png">

**Comment by mrkn** [comment]
I cannot reproduce this bug.
