### ISSUE TITLE
Is there any way to customize indentation width?

### ISSUE THREAD

**Issue by mmck328** [SciRuby/iruby#253]
As mentioned in https://github.com/SciRuby/iruby/issues/27, code cell indentation for IRuby kernel is hardcoded to 2 spaces in kernel.js.
This overrides user's preference stored in Jupyter notebook config (e.g. ~/.jupyter/nbconfig/notebook.json), so the method noted in Jupyter's doc (https://jupyter-notebook.readthedocs.io/en/stable/frontend_config.html) doesn't work.

Is there any workaround to set indentation other than 2 spaces? (like 4 spaces)

**Comment by kojix2** [comment]
Hello @mmck328 
This is kojix2 doing issue triage.

As you know, 2 spaces indentation is accepted as the way to do things.
Please give us the details about why you want to customize indentation?

For example:
* You love 4 spaces, that's all :smile_cat: .
* 4-space Ruby :notebook:  are easy to co-edit with Python engineers
* 4 Space Ruby :notebook:  are easy to manage with Python :notebook_with_decorative_cover:  .
* Your boss like 4 spaces.

**Comment by gisborne** [comment]
Guyren G Howe

**Comment by mmck328** [comment]
Thank you for reply @kojix2.
For your question, my answer is just "I love 4 spaces".
I understand setting 2-spaces indent as default is quite reasonable, from convention of Ruby community.

My concern is about that IRuby sets not only default configuration, but totally disables custom setting of Jupyter Notebook (not of IRuby), and this is unintended/unexplained behavior for me.
I tried to set custom spaces indent following Jupyter's official docs, it works for IPython kernel but doesn't work for IRuby kernel. I ended up reading kernel.js in this repo to understand this behavior.

**Comment by kojix2** [comment]
Thank you for your reply @ mmck 328.

The easiest way is to remove `kernel.js.`
 `kernel.js` is not necessary for IRuby to work.

1. Check the iruby kernel spec location.
```sh
jupyter kernelspec list
# ruby         /home/kojix2/.local/share/jupyter/kernels/ruby
```

2. Remove kernel.js
```sh
cd ~/.local/share/jupyter/kernels/ruby
rm kernel.js
