### ISSUE TITLE
Tab completion in a cell removes other lines

### ISSUE THREAD

**Issue by agarie** [SciRuby/iruby#26]
I updated to IRuby 0.2.0 recently and noticed a bug in which tab completion removes the preceding lines in the cell when I'm in the last line, or doesn't work at all when there are lines after the one I'm on. Take a look at these examples:

```ruby
puts 123
puts 'asdf'
puts IRuby::VERSION.a<TAB>
```

In this case, I can choose a method when I press <TAB>, but if I select one, the other lines are removed and the only one left is the last one (e.g. `puts IRuby::VERSION.abs`). If I press ESC and don't select a method, the cell is left as is.

```ruby
puts 123
puts 'asdf'
puts IRuby::VERSION.a<TAB>
puts "fourth line"
```

In this case, when I press <TAB> with the cursor in the third line, nothing happens.

Is there any other information you folks need? Or is this a known bug? I couldn't find anything about it in the issue tracker.

**Comment by minad** [comment]
Thx for reporting. The way how completion works was changed with the new protocol version 5.0 (IPython3/Jupyter). It seems that the complete_request/reply isn't implemented correctly.
