### ISSUE TITLE
Autocomplete replaces the current content of the prompt instead of appending to it

### ISSUE THREAD

**Issue by Stvad** [SciRuby/iruby#269]
![giflink](https://user-images.githubusercontent.com/81347/71429533-e4d1a980-267b-11ea-8db3-1d6bae9f31b7.gif)

I'm using the version from the master as per https://github.com/SciRuby/iruby/issues/268, but it also happened to me on the 0.4 as well

**Comment by ankane** [comment]
From my testing, this should be fixed when #276 is merged.

**Comment by mrkn** [comment]
I confirmed this is fixed in 0.6.0.
