### ISSUE TITLE
2 spaces indentation instead of 4

### ISSUE THREAD

**Issue by agarie** [SciRuby/iruby#27]
Exactly as the title says. The automatic indentation is 4 spaces, but the default for Ruby is 2. 

According to this [stackoverflow answer](http://stackoverflow.com/a/24615436/1015273), it should be quite simple to modify.

**Comment by minad** [comment]
Try to add it to kernel.js

Am 29. Mai 2015 05:47:40 MESZ, schrieb Carlos Agarie <notifications@github.com>:

**Comment by agarie** [comment]
Wonderful. Thanks, @minad! :tada:
