### ISSUE TITLE
Idea: Display multiple results from a cell

### ISSUE THREAD

**Issue by ankane** [SciRuby/iruby#274]
In Python notebooks, you can do:

```python
display(1)
display(2)
display(3)
```

To show:

```txt
1
2
3
```

This is great for things like showing multiple images. It'd be great to be able to do this in Ruby as well.

**Comment by kojix2** [comment]
Hi Andrew Kane!

I think `IRuby.display` is useful for this purpose. 

```ruby
IRuby.display(1)
IRuby.display(2)
IRuby.display(3)
```

You can display images too.

![image](https://user-images.githubusercontent.com/5798442/80800051-74b3d100-8be3-11ea-92ae-6e92c9968228.png)


But displaying IO object is not recommended. https://github.com/SciRuby/iruby/pull/113

**Comment by ankane** [comment]
Awesome, works great - thanks @kojix2! (saw `IRuby::Display.display` but missed that one)
