### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by minad** [SciRuby/iruby#28]
Hi @domitry,

could you port your https://github.com/minad/iruby/pull/30 patches to the new version? Unfortunately I cannot test on windows.

**Comment by cboos** [comment]
Link above is stale. Do you have a copy of these patches? I'm willing to give it a try, but a starting point would help.

**Comment by v0dro** [comment]
^ Go to sciruby/iruby.

**Comment by minad** [comment]
@cboos Just test it under windows and see if it works or if something goes wrong. Then you could try to fix it :)

**Comment by minad** [comment]
I guess it should work again? @domitry
