### ISSUE TITLE
Detaching from minrk/iruby

### ISSUE THREAD

**Issue by mrkn** [SciRuby/iruby#285]
I will request to detach this repository from minrk/iruby to GitHub.

**Comment by mrkn** [comment]
https://support.github.com/ticket/personal/0/972717

**Comment by kojix2** [comment]
I agree with you. This banner shows up every time and takes up some space. It would be nice if the banner could be hidden.

![image](https://user-images.githubusercontent.com/5798442/107135492-8da19d80-693e-11eb-8aa8-d861fc4d3265.png)

**Comment by mrkn** [comment]
Detaching this repository from the original parent has been done by GitHub.
Please fork from this repository again.
