### ISSUE TITLE
Kernel should not check signatures when key is empty

### ISSUE THREAD

**Issue by willwhitney** [SciRuby/iruby#29]
This is the same as https://github.com/IRkernel/IRkernel/pull/139, but for this kernel.

The [messaging spec](http://ipython.org/ipython-doc/stable/development/messaging.html#the-wire-protocol) says: 

> To disable authentication and signature checking, set the key field of a connection file to an empty string.

Even with the key set to the empty string, IRuby throws an error when it gets messages that have empty signature fields, which means that it does not currently work with [Hydrogen](https://atom.io/packages/hydrogen) (https://github.com/willwhitney/hydrogen/issues/49)

**Comment by minad** [comment]
@willwhitney thx for reporting. Could you please check if it works now with Hydrogen?
