### ISSUE TITLE
Include examples using scientific gems in sample notebooks

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#30]
Show how each of the following gems can be used with iruby:
* NMatrix
* Nyaplot
* Daru
* Statsample

There can be examples that use daru/nmatrix for storing data, statsample for analysis and nyaplot to plot it.

**Comment by v0dro** [comment]
@minad I will submit a few notebooks if you're ok with this.

**Comment by minad** [comment]
great, do that!

**Comment by minad** [comment]
I suggest we could create a separate repository for those examples, what do you think?Maybe @mohawkjohn could create a repository sciruby/sciruby-notebooks?

As I was suggesting on the mailing list we could also provide a Dockerfile inside the repository. There are already such repositories with Dockerfiles around, e.g.

* https://github.com/jupyter/docker-demo-images (dockerfile for try.jupyter.org)
* https://github.com/audy/docker-sciruby-notebook (also contains an example notebook)
* https://github.com/domitry/sciruby-docker (only dockerfile)
* https://github.com/nagachika/docker-iruby (only dockerfile)
* https://github.com/akkky/iruby-docker (only dockerfile)

**Comment by minad** [comment]
Ah I have just seen that I can also create repositories here -> https://github.com/SciRuby/sciruby-notebooks

Summoning @audy @domitry @nagachika @akkky

**Comment by v0dro** [comment]
Sure that sounds great.

I'll submit my notebooks there itself.
