### ISSUE TITLE
self no longer works with PlainBackend

### ISSUE THREAD

**Issue by UliKuch** [SciRuby/iruby#303]
Hi!
Thanks for maintaining this Gem, I really enjoy using Jupyter notebooks with Ruby 🙂

Unfortunately, when using the `PlainBackend` in version 0.6 or 0.7 together with Ruby 3.0.1, I am having issues with the `self` object. It no longer evaluates to `main`, but to some other object:
![grafik](https://user-images.githubusercontent.com/53051039/120217603-defcd200-c238-11eb-9406-a1187a1812b5.png)
As I verified by running the line in an irb session, the object seems to be the one created by https://github.com/SciRuby/iruby/blob/fb20cc30c2cb6e104b5398a6a6d907c699743b5a/lib/iruby/backend.rb#L42

Because of this, I can no longer include any modules inside a notebook.

When I remove the `dup` in the quoted line, everything seemed to work fine, but I am not sure if that breaks anything else.

Or am I missing some error on my part here? I am running my notebooks via the [jupyter_on_rails gem](https://github.com/Yuki-Inoue/jupyter_on_rails/), but the issue does not seem to lie there.

**Comment by kojix2** [comment]
> Because of this, I can no longer include any modules inside a notebook.

Could you please explain more about this point?

**Comment by UliKuch** [comment]
> Could you please explain more about this point?

If, inside a notebook, I try including a module, I receive a `NoMethodError`:

```ruby
module Foo
  def bar
    puts "baz"
  end
end

include Foo
# NoMethodError: undefined method `include' for #<Object:0x00007f87fc58d960 @prompt={:PROMPT_I=>"3.0.1 :%03n > ", :PROMPT_S=>"3.0.1 :%03n%l> ", :PROMPT_C=>"3.0.1 :%03n > ", :PROMPT_N=>"3.0.1 :%03n?> ", :RETURN=>" => %s \n", :AUTO_INDENT=>true}>
# (irb):in `<main>'
```
In version 0.5, this used to work fine. And in any regular irb shell it works, too.

Extending the module instead seems to work though:
```ruby
extend Foo
# #<Object:0x00007f87fc58d960 @prompt={:PROMPT_I=>"3.0.1 :%03n > ", :PROMPT_S=>"3.0.1 :%03n%l> ", :PROMPT_C=>"3.0.1 :%03n > ", :PROMPT_N=>"3.0.1 :%03n?> ", :RETURN=>" => %s \n", :AUTO_INDENT=>true}>

bar
# baz
```

**Comment by kojix2** [comment]
I see. I understand.
I was not aware of this problem.

**Comment by mrkn** [comment]
@UliKuch Thank you for reporting this issue.  This is bug.  I'll fix it asap.

**Comment by mrkn** [comment]
@UliKuch Please try the version 0.7.2.

**Comment by kylekyle** [comment]
Works great! Thanks!

**Comment by UliKuch** [comment]
Including a module now works fine, thanks a lot @mrkn !
