### ISSUE TITLE
Suggestion: to_iruby should take precedence over other display methods

### ISSUE THREAD

**Issue by ankane** [SciRuby/iruby#314]
Hi, currently, if an object has methods like `to_html` or `to_png`, they'll take precedence over `to_iruby`. If an object has `to_iruby` defined, it seems like that should be preferred.

```ruby
class A
  def to_html
    "HTML"
  end
  
  def to_iruby
    ["text/plain", "IRUBY"]
  end
end

A.new
```

Shows `HTML` instead of `IRUBY`

**Comment by ankane** [comment]
Related, it looks like iRuby calls all the display methods, even if it only renders one.

```ruby
class A
  def to_html
    puts "called to_html"
    "HTML"
  end
  
  def to_png
    puts "called to_png"
  end
  
  def to_iruby
    puts "called to_png"
    ["text/plain", "IRUBY"]
  end
end

A.new
```

Prints

```txt
called to_png
called to_html
called to_png
```

And renders `HTML`

**Comment by ankane** [comment]
It looks like one way around this is to define a `to_iruby_mimebundle` method.

```ruby
def to_iruby_mimebundle(**)
  [{"text/plain" => "IRUBY"}, {}]
end
```

**Comment by mrkn** [comment]
@ankane I recommend using `to_iruby_mimebundle` instead of `to_iruby` now.

**Comment by ankane** [comment]
Hey @mrkn, thanks for the response and context! Will use that.
