### ISSUE TITLE
Issue with ipython and/or vscode?

### ISSUE THREAD

**Issue by mattlindsey** [SciRuby/iruby#329]
I have installed Jupyter with conda, and iruby according to instructions in the README, and I have 2 ways to use jupyter:

- `iruby notebook` (given in the README)
- In VSCode with the Jupyter extensions

The first method gives the error `[TerminalIPythonApp] WARNING | File 'notebook' doesn't exist`
(although `conda info notebook` says that notebook is installed)

The second seems to work but is difficult to manage which gems and version are needed.  Ruby 3.2.1.
Any help to get it working better appreciated!

**Comment by mattlindsey** [comment]
This seems to work best using `jupyter notebook` command now, so I'll close this.

**Comment by kojix2** [comment]
My understanding is that commands such as `iruby notebook` etc, are left only for past compatibility. 
Yes. Please use the `jupyte` command.
