### ISSUE TITLE
Can't add a method to String class in Jupyter-lab

### ISSUE THREAD

**Issue by nmingotti** [SciRuby/iruby#333]
Hi, as title says, *in Jupyter-lab* , here is an example how what does not work
```
class String 
    def fs()
        return "foobar"
    end
end 
#
"123".fs
```
I get "undefined method `fs' for "123":String". Maybe I am missing something silly here but this is very useful to have. bye

**Comment by kojix2** [comment]
Hi @nmingotti 

The reason for this is that we are in `Object`, not `main`.

```rb
class ::String 
    def fs()
        return "foobar"
    end
end 
# fs()
"123".fs.
```

will returns the expected result.

See https://github.com/SciRuby/iruby/issues/326

I am not sure why iruby does this.

**Comment by nmingotti** [comment]
Thank you, this is an important productivity feature to have for me.
I close the issue, but it would be great if somebody could explain why it is this way.
