### ISSUE TITLE
How to inline an image in a jupyter-labnotebook ?

### ISSUE THREAD

**Issue by nmingotti** [SciRuby/iruby#336]
Hi, 
I am trying to work with iruby in Jupyter-lab. Suppose i have a PNG generated by previous calculations. I wish to add (inline) this PNG into the notebook, as a result cell, how can i do ? Is it possible ? 

bye
Nicola

**Comment by kojix2** [comment]
Hi @nmingotti 

Are you looking for IRuby#display ?
Or some other function?

**Comment by nmingotti** [comment]
I found a way to solve indirectly :) Thank you @kojix , U r very nice !
```
IRuby.html('<img src="./simple1.png">')
```
