### ISSUE TITLE
Include date in headers

### ISSUE THREAD

**Issue by rgbkrk** [SciRuby/iruby#340]
When testing out this kernel with https://github.com/zed-industries/zed/pull/12062, I noticed that `date` is not in the headers. I'd love to see that added in so that I don't have to make `date` optional in my rust structures.

**Comment by kojix2** [comment]
Hi @rgbkrk 

Thank you for your report. 
IRuby currently has no active developers and has no plans to keep up with the latest Jupyter protocol.
Still, I would like to hear a little more detail on your report.

If I understand correctly, you are reporting that the  [Message Header](https://jupyter-client.readthedocs.io/en/latest/messaging.html#message-header) does not contain a `date` field, right?

Maybe we can modify the code here to add a date field...

https://github.com/SciRuby/iruby/blob/f341266ea123a0a916b17b148742bb101b6c0a41/lib/iruby/session.rb#L79-L85

**Comment by rgbkrk** [comment]
You don't have to implement all the messages, but I'd at least bring it up to version 5.1 compliance where date is a required field. https://jupyter-client.readthedocs.io/en/latest/messaging.html

**Comment by rgbkrk** [comment]
Thank you @ebababi! @kojix2, who has the ability to ship a patch release of the gem for iruby?

**Comment by kojix2** [comment]
The owners of the gem are @minad, @mrkn, @domitry, @v0dro, and @kozo2.

**Comment by kozo2** [comment]
@kojix2 Can I ask you to ship that release? I invited you to the owner of https://rubygems.org/gems/iruby .

**Comment by kojix2** [comment]
Sure, @kozo2. Thank you for the invitation.
I will review the changes and would like to proceed with shipping the release soon.

**Comment by kojix2** [comment]
Version 0.8.0 has been uploaded to the rubygem server. There may still be room for improvement.  If you find ways to improve it, pull requests are welcome.
