### ISSUE TITLE
Cannot load on homebrew

### ISSUE THREAD

**Issue by patrickjonesdotca** [SciRuby/iruby#35]
Currently seeing this error when launching notebook using Python3
```ruby
gems/iruby-0.2.5/lib/iruby/command.rb:73:in `require': cannot load such file -- iruby (LoadError)
```

**Comment by v0dro** [comment]
see #31. You need a Gemfile with `gem 'iruby'` in your PWD.

**Comment by v0dro** [comment]
You just need to run iruby from a folder which contains a Gemfile that has `gem 'iruby'` in it.

And @minad I really think we need to resolve this issue, with or without bundler. More people seem to be having the same problem.

**Comment by minad** [comment]
@v0dro gladly, if you propose a solution and provide a patch. A possible hack could be to check if you are running `iruby` from a directory which doesn't contain iruby in it and print a warning or even terminate then.

@patrickjonesdotca can you confirm that it is a problem with the gemfile?

**Comment by v0dro** [comment]
I'll look into it.
