### ISSUE TITLE
NoMethodError with 'build_statement'

### ISSUE THREAD

**Issue by Chen-Suyi** [SciRuby/iruby#351]
Following the instructions, I have successfully installed iruby, and I can open a Jupyter notebook and select Ruby kernel on VSCode. However, when I tried to run some simple commands, NoMethodError occurred. I have no idea what happened. It seems related to iruby.
<img width="926" alt="image" src="https://github.com/user-attachments/assets/9ab51461-4462-4de6-b588-ca48a1ffba38">

**Comment by kojix2** [comment]
Hi Chen Suyi

Thank you for your report.
This error is saying that the object of IRB::Irb does not have `build_statement` method. 
Please check if the following code can be executed in your environmen.

```rb
require “irb”
i = IRB::Irb.new
s = i.build_statement(“puts ‘hello world’”)
i.context.evaluate(s, 0)
````

It may be useful to run the `jupyter kernelspec list` command to check which Ruby is used in Jupyter.

**Comment by Chen-Suyi** [comment]
> Hi Chen Suyi
> 
> Thank you for your report. This error is saying that the object of IRB::Irb does not have `build_statement` method. Please check if the following code can be executed in your environmen.
> 
> ```ruby
> require “irb”
> i = IRB::Irb.new
> s = i.build_statement(“puts ‘hello world’”)
> i.context.evaluate(s, 0)
> ```
> 
> It may be useful to run the `jupyter kernelspec list` command to check which Ruby is used in Jupyter.

<img width="934" alt="image" src="https://github.com/user-attachments/assets/b099bd83-94de-424c-b874-e4db8ebee2ec">

Thanks for your prompt reply. However, it seems it doesn't work.

**Comment by kojix2** [comment]
Try running it outside of Jupyter.

For example, type `irb` in your terminal to start the Ruby interpreter. 
Alternatively, you can execute it using `ruby test.rb` or similar commands.

**Comment by Chen-Suyi** [comment]
> ```ruby
> require “irb”
> ```

<img width="931" alt="image" src="https://github.com/user-attachments/assets/c74f5d98-b680-4598-b169-54ce11d99da6">
It failed again.

**Comment by kojix2** [comment]
It seems that irb is not working properly. Does the irb command itself work?

What platform are you using, and how did you install Ruby? (For example, what OS are you using, and which package manager did you use to install Ruby? rbenv or RVM?)

If you're lucky, simply running gem update irb may resolve the issue.

**Comment by Chen-Suyi** [comment]
> ```ruby
> s = i.build_statement(“puts ‘hello world’”)
> ```

<img width="571" alt="image" src="https://github.com/user-attachments/assets/a83de83e-f3b5-436b-aa22-b761b5db9f04">
It failed when using irb command itself.

I installed Ruby on MacOS using Homebrew. Following the official guideline, I use this command:
`brew install ruby`

**Comment by kojix2** [comment]
![image](https://github.com/user-attachments/assets/30e8c409-eed2-439e-806d-7e949f387739)
Hmm, this error is quite strange.

Can you run `gem update irb` without any errors?

**Comment by Chen-Suyi** [comment]
<img width="571" alt="image" src="https://github.com/user-attachments/assets/4c69bef6-dc78-4da2-82da-c16536eb5758">



It is really weird. After running `gem update irb` , irb works itself, but it fails via a .rb file.



<img width="572" alt="image" src="https://github.com/user-attachments/assets/8b7eb941-dffd-4d47-82d9-d1d48341d2ea">
<img width="930" alt="image" src="https://github.com/user-attachments/assets/f5c8c9f2-a7be-453b-9be3-0f2799c3a5e3">

**Comment by Chen-Suyi** [comment]
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/c0d843e6-f8ac-402a-a92d-74645bdda433">

Anyway, this time it works on Jupyter notebook. Though it still fails on .rb file, it does not matter I guess.

Thank you for your time and consideration.

**Comment by kojix2** [comment]
If you must, you can install ruby from conda/mamba. (This method is not recommended, but may be useful in the world of high-performance computing.)

https://dev.to/kojix2/using-ruby-with-conda-1hn
