### ISSUE TITLE
Download as Ruby fails

### ISSUE THREAD

**Issue by DrXyzzy** [SciRuby/iruby#38]
Try this at at try.jupyter.org:

1. Open Ruby notebook.
2. Put in one line, e.g.
  puts "hello"
3. Use menu File > Download as > Ruby (rb). Result is error:
500 : Internal Server Error
The error was:
nbconvert failed: FileExtension trait 'file_extension' does not begin with a dot: 'rb'

Note that unlike other Download formats in the pulldown menu, "Ruby (rb)" does not have a dot before the extension in parens.

Workaround is to download as Python and rename the .py file to .rb.  Bug reproduced using rvm with Ruby 2.2 and iruby gem on OS X 10.10.3 laptop.

**Comment by dmorrill10** [comment]
After installing from `master`, this still occurs for me, except "Ruby (.rb)" does have a dot before the extension. The message I get is very slightly different as well,
 `nbconvert failed: FileExtension trait 'file_extension' does not begin with a dot: u'rb'`.

I am using `rbenv` with Ruby 2.1.2 on Ubuntu 14.04.

**Comment by minad** [comment]
Did you recreate the notebook. This is definitely fixed in master, see https://github.com/SciRuby/iruby/commit/50a6860fc734546309cb16f9405402efec863657

**Comment by dmorrill10** [comment]
Oops, I did not. You're correct, recreating the notebook makes this work, thanks for your help.
