### ISSUE TITLE
Implement interactive widgets and handle user input

### ISSUE THREAD

**Issue by minad** [SciRuby/iruby#4]
See https://github.com/minad/iruby/issues/37

**Comment by jnv** [comment]
For reference, this is handled on the `stdin` socket: http://ipython.org/ipython-doc/dev/development/messaging.html#messages-on-the-stdin-router-dealer-sockets

This seems to be an actual implementation: https://github.com/ipython/ipython/blob/e2778c5f4047d03f5f025bd53d1704a0cf9f0337/IPython/kernel/zmq/kernelbase.py#L654-L692

**Comment by minad** [comment]
@domitry I have removed your widget class for now. I think this should go into a separate gem iruby-widgets. However I kept IRuby::Conn since this is more or less core functionality. What do you think?

**Comment by minad** [comment]
See https://github.com/ipython/ipywidgets/issues/41

**Comment by kylekyle** [comment]
Do the input widgets satisfy this?
