### ISSUE TITLE
please revert to ffi-rzmq, rbczmq gemspec is broken

### ISSUE THREAD

**Issue by mikofski** [SciRuby/iruby#42]
see https://github.com/methodmissing/rbczmq/issues/41

**Comment by mikofski** [comment]
well you're probably not going to do that so, is there anyway to get iruby on windows using Ruby Devkit?

**Comment by minad** [comment]
Well, you just have to fix rbczmq. 

Otherwise - the codehase allows to support both, ffi-rzmq and rbczmq. Take a look at the Session class which encapsulates the whole 0mq stuff. You can provide both implementations of the Session class if you want. For the ffi-rbzmq you just have to look at the history.

**Comment by minad** [comment]
But I have to add, such a patch can only be accepted when I get a working test suite. Otherwise it is just getting out of hands.

**Comment by maxyeg** [comment]
How can I revert to ffi-rzmq?

**Comment by v0dro** [comment]
I've posted a possible fix to the rbczmq issue: https://github.com/methodmissing/rbczmq/issues/41

Can someone with a Windows machine please try it out and see if it works?

**Comment by minad** [comment]
Test

Am 4. September 2015 18:13:06 MESZ, schrieb Maxim <notifications@github.com>:

**Comment by jmarrec** [comment]
This is still a problem by the way, doesn't seem to be getting much traction on https://github.com/methodmissing/rbczmq/issues/41 either.

**Comment by domitry** [comment]
I installed rbczmq to Windows, but it doesn't work. (https://github.com/methodmissing/rbczmq/issues/52)

I myself didn't try on Mac or FreeBSD, but I heard that installing fails on both environments.
(https://github.com/methodmissing/rbczmq/issues/42, http://d.hatena.ne.jp/msll/20151116)

I think that adding compatibility with ffi-rzmq and removing rbczmq from runtime_dependency is better. (As pry is still in "recommended gems")
