### ISSUE TITLE
Possible solution to requiring a Gemfile in the iruby PWD.

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#43]
A possible solution to having a Gemfile in the directory where the iruby command is run would be create a temporary file called `Gemfile` and add all the gems yielded by `gem list` to that file, in the format required by Gemfiles.

Once the notebook is terminated, we can delete the Gemfile as a cleanup operation.

This can be done only if a Gemfile is not present in the directory, in which case the default Gemfile will be used.

**Comment by minad** [comment]
no gemfile is required in the current pwd. this was fixed in https://github.com/SciRuby/iruby/commit/45fd71b046fada03f42570107443e1d18bc78006

**Comment by v0dro** [comment]
My bad.
