### ISSUE TITLE
iruby-0.2.7/lib/iruby/utils.rb:8:in `display': undefined method `session' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tansaku** [SciRuby/iruby#48]
I get this really weird issue with iRuby when I just add the nyaplot gem on osx - see https://github.com/domitry/nyaplot/issues/55 for more details, but just wondering if anyone understands the iruby portion of the error message:

```
iruby-0.2.7/lib/iruby/utils.rb:8:in `display': undefined method `session' for nil:NilClass (NoMethodError)
```

**Comment by domitry** [comment]
Solved. (See https://github.com/domitry/nyaplot/issues/55.)
