### ISSUE TITLE
Console issues

### ISSUE THREAD

**Issue by minad** [SciRuby/iruby#5]
Currently only the notebook is working well since this was the focus. However we should also get the console working well:
- https://github.com/minad/iruby/issues/52 (Multiline methods not working)
- https://github.com/minad/iruby/issues/51 (Syntax highlighting)
- https://github.com/minad/iruby/issues/47 (Quit/exit not working)
- https://github.com/minad/iruby/issues/48 (Autocomplete issue)

**Comment by spacewander** [comment]
I am wonder why people need to use console...
The web UI version can meet much of the demand, and it's impossible to share the same session between web and console.
What is the console mainly working for?

**Comment by minad** [comment]
Actually I don't know. That's the reason there are so many issues right now. However the qtconsole makes sense since it supports embedded images etc

**Comment by spacewander** [comment]
Seems those problems are caused by `ipython console`.
IRuby currently use `ipython console` as the frontend of `console` mode.
So the indent and syntax highlight are for python instead of ruby.

**Comment by spacewander** [comment]
If we can define `pry` as the frontend of the console mode, those problems can be solved. 
However currently we just can write our own kernel - but not another interface.
