### ISSUE TITLE
how to pass kernel parameters?

### ISSUE THREAD

**Issue by runa** [SciRuby/iruby#56]
Hi!
We've upgraded from ipython to jupyter and everthing seems to be working fine.

The only missing part, is that I'm not too sure how to pass [this parameters](https://github.com/SciRuby/iruby/blob/master/lib/iruby/command.rb#L63) to the kernel.

We used to do this using `KernelManager.kernel_cmd` but it's deprecated in Jupyter.

Specificaly, I'm wondering how to pass the `boot_file` path to iruby.

thanks!

**Comment by domitry** [comment]
Run `jupyter --paths`

```
config:
    /home/username/.jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/username/.local/share/jupyter
    /home/username/anaconda/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /run/user/1000/jupyter
```

You can find `kernels/ruby/kernel.json` in a directory listed in `data` section.
It is in ` /home/username/.local/share/jupyter` in my case.
`kernel.json` is as shown below.

```json
{"argv":["/usr/local/bin/iruby"],"display_name":"Ruby 2.1.5","language":"ruby"}
```

Rewrite it as:

```json
{"argv":["/usr/local/bin/iruby"],"display_name":"Ruby 2.1.5","language":"ruby", "foo"}
```

Then IRuby will try to run `require 'foo'` internally.

**Comment by domitry** [comment]
Sorry, the content of JSON file was wrong. Now fixed.

**Comment by runa** [comment]
Great, thanks!

Thanks for your effort, we use iruby daily; 

Congratulations and thank you again.

**Comment by domitry** [comment]
:)
