### ISSUE TITLE
readlink() function is unimplemented on this machine (NotImplementedError) - Windows 7 x64

### ISSUE THREAD

**Issue by MatthewSteen** [SciRuby/iruby#65]
I followed the Windows installation instructions on the master branch README and `gem install iruby -v 0.1.13` for Python27. However, I got the following:

>$ iruby notebook
[ProfileCreate] Generating default config file: u'C:\\Users\\Matt\\.config\\iruby\\profile_d                                           efault\\ipython_config.py'
[ProfileCreate] Generating default config file: u'C:\\Users\\Matt\\.config\\iruby\\profile_d                                           efault\\ipython_kernel_config.py'
[ProfileCreate] Generating default config file: u'C:\\Users\\Matt\\.config\\iruby\\profile_d                                           efault\\ipython_console_config.py'
[ProfileCreate] Generating default config file: u'C:\\Users\\Matt\\.config\\iruby\\profile_d                                           efault\\ipython_qtconsole_config.py'
[ProfileCreate] Generating default config file: u'C:\\Users\\Matt\\.config\\iruby\\profile_d                                           efault\\ipython_notebook_config.py'
[ProfileCreate] Generating default config file: u'C:\\Users\\Matt\\.config\\iruby\\profile_d                                           efault\\ipython_nbconvert_config.py'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/iruby-0.1.13/lib/iruby/command.rb:89:in `readlink':                                            readlink() function is unimplemented on this machine (NotImplementedError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/iruby-0.1.13/lib/iruby/command.rb:89:in                                            `create_profile'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/iruby-0.1.13/lib/iruby/command.rb:62:in                                            `run_ipython'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/iruby-0.1.13/lib/iruby/command.rb:18:in                                            `run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/iruby-0.1.13/bin/iruby:6:in `<top (requ                                           ired)>'
        from C:/Ruby200-x64/bin/iruby:23:in `load'
        from C:/Ruby200-x64/bin/iruby:23:in `<main>'
Creating profile directory C:/Users/Matt/.config/iruby/profile_default

**Comment by domitry** [comment]
IRuby v0.1.13 is deprecated. See [README.md](https://github.com/SciRuby/iruby#windows) and install the newest version of IRuby instead.

**Comment by MatthewSteen** [comment]
@domitry so the instructions at the top in bold are outdated?

>The current master branch and gem version >= 0.2 are compatible with IPython3/Jupyter. If you require IPython2 support, please install an older gem version < 0.2 or use the branch ipython2

I would like to install for Python27, is IRuby compatible?

**Comment by domitry** [comment]
> so the instructions at the top in bold are outdated?

Oops, no, but maybe the version of IPython installed in your environment is not 2.x. Please try `ipython --version`. If the result is higher than 3, remove IPython once and run `pip install ipython==2.1.0` then IRuby v0.1.13 will work.

 BTW you can also install the newest version of IRuby for Python2.7. v0.1.13 is for **IPython** 2.x, not **Python** 2.x. Just try commands listed in README.md.

**Comment by MatthewSteen** [comment]
@domitry thanks for the help, but using `%%ruby` in an IPython cell is working better for me.
