### ISSUE TITLE
Question: can I use iruby with Ruby 2.0.0?

### ISSUE THREAD

**Issue by jmarrec** [SciRuby/iruby#66]
Hi,

This isn't an issue but rather a question. I see that for the current iteration, the min required version for ruby is 2.1.0.

I need to use ruby 2.0.0 because I'm using it to access one (and actually only one) API that works only on 2.0.0.

Can I use IRuby with ruby 2.0.0? How?

Thanks !

**Comment by MatthewSteen** [comment]
+1

**Comment by v0dro** [comment]
Might this be useful : https://github.com/SciRuby/iruby/issues/60

**Comment by domitry** [comment]
I don't know the reason but maybe IRuby will not work on Ruby<2.1.x. See: https://github.com/SciRuby/iruby/commit/866df2812ec998ebc64e7474e9ea8aa516227480

I think some lines written in pure Ruby prevent the compatibility with Ruby2.0.x. If that's true you can write a patch for this issue.

**Comment by mrkn** [comment]
The latest IRuby couldn't be used on Ruby 2.0.0 because it depends on `Binding#local_variable_defined?` method that is introduced from Ruby 2.1.0.

**Comment by MatthewSteen** [comment]
@jmarrec I might have to revisit this now that OpenStudio 2.x uses Ruby 2.2.4.
