### ISSUE TITLE
iruby

### ISSUE THREAD

**Issue by alexkowalenko** [SciRuby/iruby#67]
I'm having a crash, which shows up by just running, iruby. I'm running on Mac OX 10.11, ruby 2.3. Could it be something with it's interaction with zeromq?

alex@Oriente[215] iruby
ruby(6972,0x7fff79ff3000) malloc: *** error for object 0x7fc1b43ca878: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Jupyter Console 4.1.0

print 'x'

^C
KeyboardInterrupt in interact()

**Comment by jorisvanzundert** [comment]
I think you're guessing right. Take a look at #64 and #70. Hope that works.

**Comment by kylekyle** [comment]
Between issues #70, #80, and #90, this problem is pretty well documented. I'll close this, but please reopen if you think this is something unrelated.
