### ISSUE TITLE
Dead kernel

### ISSUE THREAD

**Issue by jorisvanzundert** [SciRuby/iruby#70]
Hi,

Very much wanting to use iRuby, but when I 'jupyter notebook' I run into a kernel restart and eventually a dead kernel. This seems to be the most useful stuff from the trace:

ruby /Users/joris/.rvm/gems/ruby-2.2.1/bin/iruby kernel /Users/joris/Library/Jupyter/runtime/kernel-3b9a3d33-b719-4250-af57-586cd31d356e.json(66682,0x7fff79517300) malloc: *** error for object 0x7f862370ac08: incorrect checksum for freed object - object was probably modified after being freed

(Jupyter 4.0.6, Ruby 2.2.1 (rvm))

Any ideas what might be going wrong here?

Best
--Joris

**Comment by jorisvanzundert** [comment]
Fixed: I had to version down zmq @4.1.4 (MacPorts) to zmq3 @3.2.5.
(First: "$sudo port uninstall --dependents zmq @4.1.4" Then: "$sudo port install zmq3")
Seems similar to issue #64

**Comment by tabetomo** [comment]
in my case, ffi-rzmq seems not work.

Following the next page, I decided to 1) install system zeromq and czmq, then 2) install rbczmq using the system zeromq and czmq.
  http://qiita.com/mrkn/items/78196ed59266f58dcb64

> gem uninstall ffi-rzmq   # if you installed ffi-rzmq and it didnt work
> brew install zeromq czmq
> gem install rbczmq -- --with-system-libs

Currently it seems ok

**Comment by shmilee** [comment]
I'm using Arch.

1. `gem install rbczmq` gives me an error:
   ```
zdir.c:156:9: 错误：‘readdir_r’ is deprecated [-Werror=deprecated-declarations]
         int rc = readdir_r (handle, entry, &result);
         ^~~
In file included from ../include/czmq_prelude.h:257:0,
                 from ../include/czmq.h:31,
                 from zdir.c:35:
/usr/include/dirent.h:183:12: 附注：在此声明
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
zdir.c:159:13: 错误：‘readdir_r’ is deprecated [-Werror=deprecated-declarations]
             rc = readdir_r (handle, entry, &result);
             ^~
In file included from ../include/czmq_prelude.h:257:0,
                 from ../include/czmq.h:31,
                 from zdir.c:35:
/usr/include/dirent.h:183:12: 附注：在此声明
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
   ```
  Maybe, the  “fat” gem, rbczmq , includes too old source code for CZMQ libraries.

2. `gem install ffi-rzmq` works well. 

3.  Use arch package manager  pacman to install `zeromq 4.1.5-1`, `czmq 3.0.2-2`, then

   ```
gem uninstall ffi-rzmq ffi-rzmq-core ffi
gem install rbczmq -- --with-system-libs
   ```
   This is what I'm using.

   ```
[$] gem list                                                                            :( 1

*** LOCAL GEMS ***

bigdecimal (1.2.8)
bond (0.5.1)
data_uri (0.1.0)
did_you_mean (1.0.0)
io-console (0.4.5)
iruby (0.2.9)
json (1.8.3)
mimemagic (0.3.2)
minitest (5.8.3)
multi_json (1.12.1)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rbczmq (1.7.9)
rdoc (4.2.1)
test-unit (3.1.5)
   ```

**Comment by nilehmann** [comment]
Trying to use it in arch. `gem install rbczmq` gives me the same error than @shmilee. Installing `zeromq4.1.5` with pacman and `czmq4.0.1` from the AUR, and then running `gem install rbczmq -- --with-system-libs` allows me to install the gem. When I try to use the kernel I get the following error.

```
ruby /home/nlehmann/.rvm/gems/ruby-2.3.2/bin/iruby kernel /run/user/1000/jupyter/kernel-2941fb56-cbea-4bea-ac7d-fb85e24ada8a.json: symbol lookup error: /home/nlehmann/.rvm/gems/ruby-2.3.2/gems/rbczmq-1.7.9/lib/rbczmq_ext.so: undefined symbol: zmutex_new
```
