### ISSUE TITLE
Error with gnuplotrb

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/iruby#73]
While running [this](https://github.com/SciRuby/sciruby-notebooks/blob/master/Data%20Analysis/Daru%20Demo.ipynb) notebook, I encountered the following error while running 27th cell.

```ruby
index  = Daru::DateTimeIndex.date_range(:start => '2012-4-2', :periods => 1000)

vector = Daru::Vector.new(1000.times.map {rng.call}, index: index)

vector = vector.cumsum

rolling_mean = vector.rolling_mean 60

​

GnuplotRB::Plot.new(

  [vector      , with: 'lines', title: 'Vector'], 

  [rolling_mean, with: 'lines', title: 'Rolling Mean'],

  xlabel: 'Time', ylabel: 'Value'

)

Errno::ENOENT: No such file or directory - gnuplot
/usr/local/rvm/gems/ruby-2.2.1/gems/gnuplotrb-0.3.1/lib/gnuplotrb/staff/settings.rb:71:in `popen'
/usr/local/rvm/gems/ruby-2.2.1/gems/gnuplotrb-0.3.1/lib/gnuplotrb/staff/settings.rb:71:in `validate_version'
/usr/local/rvm/gems/ruby-2.2.1/gems/gnuplotrb-0.3.1/lib/gnuplotrb/staff/settings.rb:38:in `gnuplot_path='
...
```
Full error message: http://pastebin.com/F2qhYrPB

The same cell run fine in irb, so I guess the problem is not with my installation.

**Comment by lokeshh** [comment]
@v0dro Could you help?

**Comment by v0dro** [comment]
Weird. @dilcom @domitry @minad any ideas?

**Comment by dilcom** [comment]
@lokeshh @vodro I believe GnuplotRB can't find gnuplot executable. You probably need to install it or add to your PATH if it's already installed.

I'll add proper error message for such cases in nearest future :+1:

**Comment by lokeshh** [comment]
I am also having problem with other gems. 
For example, `statsampe` works fine in IRB but in iRuby, running 'require statsample` gives following error:

```ruby
Gem::ConflictError: Unable to activate statsample-2.0.1, because spreadsheet-1.1.1 conflicts with spreadsheet (~> 1.0.3)
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
```

**Comment by v0dro** [comment]
Ah that error is being cause because the latest daru (0.1.2) uses the latest spreadsheet and statsample uses an older version. I'll just release a new version of statsample in a while.
