### ISSUE TITLE
Not queueing commands during initialization

### ISSUE THREAD

**Issue by CGamesPlay** [SciRuby/iruby#76]
I recently upgraded from 0.1.13 to 0.2.8 and my kernel has a slow startup time (it's loading a Rails environment). The old behavior used to queue blocks to run, the new behavior drops the blocks and doesn't run them at all.

Happy to dig into this, can you point me in the right direction?

**Comment by kojix2** [comment]
Hello @CGamesPlay . Thank you for the report.
I don't know if I can help you, but there are two Rails gems:.

https://github.com/SciRuby/iruby-rails
https://github.com/Yuki-Inoue/jupyter_on_rails

If the problem continues in 2019, please comment again.

**Comment by kojix2** [comment]
I am sorry that this issue cannot be resolved. IRuby has been updated to version 0.4. This issue is out of date, so I will close it. Please let me know if you have any problems with IRuby. Thank you very much for your report.
