### ISSUE TITLE
Sample notebooks for IRuby::Input feature

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#81]
#77 adds support for IRuby::Input. Sample notebooks demoing this would be great.

**Comment by kylekyle** [comment]
The pull request [included one](https://github.com/SciRuby/iruby/blob/master/lib/iruby/input/README.ipynb).

**Comment by v0dro** [comment]
A better place to put it would be `root/notebooks`.

**Comment by kylekyle** [comment]
Feel free to move it wherever you'd like. I personally think it would be best in [sciruby-notebooks](https://github.com/SciRuby/sciruby-notebooks), but we have to actually release the feature before we document it there.

**Comment by kylekyle** [comment]
Made a [push request](https://github.com/SciRuby/sciruby-notebooks/pull/19) to add the examples to sciruby-notebooks.
