### ISSUE TITLE
Add note about kernel crashes due to invalid Gemfile in README

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#82]
Issues like #74 keep coming up every now and then. Documenting a fix in the README might mitigate some problems.

**Comment by kylekyle** [comment]
Have you played with [IRuby::Dependencies](https://github.com/jupyter-gallery/iruby-dependencies)? It might be a good alternative to using Bundler directly in IRuby.

**Comment by kojix2** [comment]
Related issue
https://github.com/SciRuby/iruby/issues/144
