### ISSUE TITLE
Latest iruby (0.2.9) doesn't work with latest pyzmq (14.3)

### ISSUE THREAD

**Issue by elricbk** [SciRuby/iruby#90]
Yesterday I tried to install `iruby` on Ubuntu 14.04. Latest IPython/Jupyter (version 4 something) was installed with `pip`. After installation of latest `iruby` with latest `rbczmq` Ruby kernel was unable to start. Jupyter log was filled with `ValueError: '<IDS|MSG>' is not in list`. Jupyter kernel code received empty multipart message and was unable to find `DELIM` in it. The problem was resolved when latest `pyzmq` was replaced with previous version (13 instead of 14). All other solutions (changing versions for `ruby`, `iruby`, `ipython`, `rbczmq`, etc.) didn't work.

**Comment by kylekyle** [comment]
As of version 14.7.0, pyzmq bundles with zeromq-4.1.2. Unfortunately, [ffi-rzmq is not compatible with zeromq-4.1.2](https://github.com/chuckremes/ffi-rzmq/issues/121). I pointed out that this broke IRuby two months back, but there's been no movement on the ticket. All I can suggest is you bump [the issue](https://github.com/chuckremes/ffi-rzmq/issues/121). I don't think there is much that can be done on this end.

**Comment by Robsteranium** [comment]
I got the iruby kernel running by specifying `ffi-rzmq` instead of `rbczmq`. Here's the contents of my Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    bond (0.5.1)
    data_uri (0.1.0)
    ffi (1.9.10)
    ffi-rzmq (2.0.4)
      ffi-rzmq-core (>= 1.0.1)
    ffi-rzmq-core (1.0.5)
      ffi
    iruby (0.2.9)
      bond (~> 0.5)
      data_uri (~> 0.1)
      mimemagic (~> 0.3)
      multi_json (~> 1.11)
    mimemagic (0.3.1)
    multi_json (1.12.1)

PLATFORMS
  ruby

DEPENDENCIES
  ffi-rzmq
  iruby

BUNDLED WITH
   1.12.1
```

I'm on using `ipython-4.2.0` with `jupyter_core-4.1.0` and `pyzmq-15.2.0` on Kubuntu 16.04.

**Comment by v0dro** [comment]
I think we should either ditch rbczmq or submit a patch to them.

**Comment by kojix2** [comment]
Hello. 
rbczmq is not recommended in 2019. 
You can use cztop or ffi-rzmq instead. 
I close this issue. Please open again if there is a problem.
