### ISSUE TITLE
Remove check_bundler

### ISSUE THREAD

**Issue by kylekyle** [SciRuby/iruby#91]
Everytime I start an IRuby kernel, I get this warning: 

```
[I 21:41:41.078 NotebookApp] Kernel started: 95fc71f4-f3cf-4752-84e7-123b4fd9868c
W, [2016-05-25T21:41:41.852455 #88264]  WARN -- : Could not load bundler: Could not locate Gemfile or .bundle/ directory
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/bundler-1.12.2/lib/bundler.rb:170:in `rescue in root'
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/bundler-1.12.2/lib/bundler.rb:166:in `root'
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/bundler-1.12.2/lib/bundler.rb:74:in `bundle_path'
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/bundler-1.12.2/lib/bundler.rb:414:in `configure_gem_home_and_path'
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/bundler-1.12.2/lib/bundler.rb:60:in `configure'
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/bundler-1.12.2/lib/bundler.rb:121:in `definition'
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.9/lib/iruby/command.rb:109:in `check_bundler'
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.9/lib/iruby/command.rb:67:in `run_kernel'
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.9/lib/iruby/command.rb:34:in `run'
/Users/kyle/.rvm/gems/ruby-2.2.3/gems/iruby-0.2.9/bin/iruby:5:in `<top (required)>'
/Users/kyle/.rvm/gems/ruby-2.2.1/bin/iruby:23:in `load'
/Users/kyle/.rvm/gems/ruby-2.2.1/bin/iruby:23:in `<main>'
/Users/kyle/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/kyle/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

This is what happens when [`check_bundler`](https://github.com/SciRuby/iruby/blob/4fa06a9e828a2868af5441afab3773014eedb38f/lib/iruby/command.rb#L106) fails. `check_bundler` also sometimes bites people that launch iruby from project directories with Gemfiles, which [breaks iruby](https://github.com/SciRuby/iruby/issues/74). 

I propose removing the `check_bundler` code and encouraging people to use [iruby-dependencies](https://github.com/jupyter-gallery/iruby-dependencies) to load gems into notebooks. It does what `check_bundler` does on individual notebooks. It is also makes sharing easier since there is a code block that can be run to load all dependencies the notebook needs.

**Comment by minad** [comment]
Could you somehow merge back this iruby-dependencies system to iruby?

**Comment by kylekyle** [comment]
@minad: absolutely! There's a bit more testing I'd like to do, but I'll submit a PR as soon as it's ready.

**Comment by kojix2** [comment]
I hope the Gemfile error will disappear.

**Comment by kojix2** [comment]
maybe #201 solved this issue, I think.
Yes, in fact, I just reduced the error messages. 

Please reopen the issue and let me know if there is anything that concerns you.

IRuby::Dependencies looks good.
Maybe we should create a list of gems that extend IRuby.
