### ISSUE TITLE
Merge Naoki's Widget branch.

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#92]
@domitry has made improvements that allow inclusion widgets in the form of videos in iruby notebook. He had done his work as part of the Ruby Association Grant 2014 - http://www.ruby.or.jp/en/news/20150415.data/nishida.pdf.

It was not integrated because Jupyter changes the API that is used for making widgets. How about we integrate it now? Here's the branch where you can see the code - https://github.com/domitry/iruby/tree/widget_support

**Comment by v0dro** [comment]
@domitry could you please post a little about how we can go about adapting widgets to the new Jupyter API?

**Comment by v0dro** [comment]
Here's the example that makes use of this: https://github.com/domitry/double_pendulum/

**Comment by kojix2** [comment]
Hello.
I do not understand this completely. But domitory's widget_support branch seems to have already been merged into the current iRuby master branch. So I close this issue. 
https://github.com/SciRuby/iruby/commit/17c41fd1d374d04e332bc7d5569ff1153e493982

On the other hand, Video Widget is interesting. This should be discussed as new issue.
