### ISSUE TITLE
Create an easy way to deploy iruby notebooks embedded in a webpage

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#93]
I think we can take advantage of Ruby's web ecosystem here and create a sort of simple to use interface to iruby that one can integrate into their web pages and take advantage of the functionality like input and widgets to take input from users and display it nicely.

Potential users can also have the advantage of combining `IRuby::Input` with say nyaplot or gnuplotrb graphs to give in some input that changes the graphs.

@zverok @kylekyle do you have ideas that come to mind here?

**Comment by zverok** [comment]
For "static" notebook (just outputs and charts) it is pretty easy to convert .ipynb to standalone HTML -- no tools except JSON parser and Markdown formatter necessary. Speaking about interactive notebooks, it may be harder. Could you please show some good examples?..

**Comment by v0dro** [comment]
Well I can think of an example, but imagine this:
* There's a webpage (client) with HTML and JS. Within this webpage there's an embedded iruby notebook which has input and output cells.
* A server will host the ruby kernel, and calls between client and server will take user input from the client, take it to the server, and bring the output from server back into the output cell of the embedded iruby notebook so that it is visible to the user.

Think of it as the same browser based architecture in the current iruby, only that the kernel runs on a different computer.

**Comment by zverok** [comment]
I'm not 100% sure that it is an important use case. Observing what analytics who I know do with R and similar tools, I assume there are 3 main cases of "showing iruby notebooks on the web":

1. Just show the results/process of some study: needs rendering to static HTML page(s) and/or PDF;
2. Provide user with one/several _interactive experiment_ like "here is some manipulators, shift them and observe that table changes" (in this case, user don't wants to see entire study, with explanations and data preparations), and do so:
  * (a) either in context of existing (frequently Rails) app: like "add _this_ to your views and _that_ to your routes, and you'll see the nice charts on page you want";
  * (b) or as a self-sufficient "just deploy this" thingy.

I assume you rather had in mind 2b case?.. I am afraid this will mean integrating IRuby with some micro-framework like Sinatra or Roda + integrate with some templating language/views system... Can't see a short way to achieve this, for now.

**Comment by kylekyle** [comment]
The Input widgets are just erector widgets with bootstrap CSS and JS, so they would be pretty easy to render from anywhere. 

The comms is harder since Jupyter provides all of that. You could make a Rack plugin that proxies a tmpnb kernel ...

**Comment by v0dro** [comment]
A bit of both 2a and 2b. Marking this as an enhancement.

**Comment by kojix2** [comment]
It's a very important and interesting idea. Google Colab and Microsoft Azure provide such services in  2019. So you can see the incredible insight of v0dro. However, this topic is beyond the scope of IRuby. I close this issue as if I were looking at history.

> Well I can't think of an example, but imagine this:
