### ISSUE TITLE
Prompter drop-down label functionality

### ISSUE THREAD

**Issue by forkster** [SciRuby/iruby#95]
Add label functionality to the prompter drop-down element to enable separate text labeling of the field.

**Comment by kylekyle** [comment]
Something like this?

```ruby
select :country, 'United States' => 'US', 'Canada' => 'CA', ...
```

**Comment by forkster** [comment]
Just a way to change the display on the left of the input.  In your above, the display text would be Country.  I want some functionality to change that text.

select :stooge, 'Moe', 'Larry', 'Curly' would show Stooge in your prompter example.  Just want an option to make it my choice of text like "Pick your favorite Stooge:" or something similar.

**Comment by kylekyle** [comment]
You can already add a custom label using the `label` named parameter:

```ruby
select :stooge, 'Moe', 'Larry', 'Curly', label: 'Choose a Stooge'
```

Feel free to reopen if that's not what you were after.
