### ISSUE TITLE
Remove Jupyter logos in favor of iruby logos in main web UI

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#96]

**Comment by kojix2** [comment]
Hello.

It is a little lonely that there is no red Ruby icon image.

As you know far more than me, today's Jupyter Notbook and Jupyter Lab do not display the language logo. To my knowledge, other major languages ​​such as Python, Julia, R do not display the logo in main web UI. So I think IRuby will not display logo too. 

I am sorry but I would like to close this issue. 
If my understanding is mistaken, please tell me.
