### ISSUE TITLE
Using iruby inputs

### ISSUE THREAD

**Issue by v0dro** [SciRuby/iruby#98]
@kylekyle @minad can you please elaborate on how the input widget functionality can be integrated with other gems?

For example, I want two form elements, one saying nmatrix row dimension and the other saying column dimension. I wrote the form for this like so:
![screenshot from 2016-06-18 19 37 00](https://cloud.githubusercontent.com/assets/2629909/16171447/91fe7500-358c-11e6-9380-101ef6339263.png)

But even after clicking done, nothing seems to happen. How does one use inputs from the iruby widgets?

**Comment by v0dro** [comment]
I'll write up a quick blog post about this explaining it in detail...

**Comment by kylekyle** [comment]
You're using it right, it's probably just a bug. Are you running the latest release or from master? Are there any messages in your JavaScript console?

**Comment by v0dro** [comment]
Using the iruby 0.2.9 from rubygems.

**Comment by v0dro** [comment]
Why is it saying 'Jupyter not defined'? By the way, I just pulled the latest master and it's still the same error.

**Comment by kylekyle** [comment]
What version of Jupyter are you running? I'm running 4.1.0:

```bash
$ jupyter --version
4.1.0
```

**Comment by v0dro** [comment]
I updated jupyter and it works. Thanks.
